// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AcmeIdentifierAuthorizationMode,
    AcmePreauthorizedIdentifierDto,
    ProtocolCertificateAssociationsRequestDto,
    RequestAttribute,
} from './';

/**
 * @export
 * @interface AcmeProfileEditRequestDto
 */
export interface AcmeProfileEditRequestDto {
    /**
     * Description of the ACME Profile
     * @type {string}
     * @memberof AcmeProfileEditRequestDto
     */
    description?: string;
    /**
     * Terms of Service URL
     * @type {string}
     * @memberof AcmeProfileEditRequestDto
     */
    termsOfServiceUrl?: string;
    /**
     * Website URL
     * @type {string}
     * @memberof AcmeProfileEditRequestDto
     */
    websiteUrl?: string;
    /**
     * DNS Resolver IP address
     * @type {string}
     * @memberof AcmeProfileEditRequestDto
     */
    dnsResolverIp?: string;
    /**
     * DNS Resolver port number
     * @type {string}
     * @memberof AcmeProfileEditRequestDto
     */
    dnsResolverPort?: string;
    /**
     * RA Profile UUID
     * @type {string}
     * @memberof AcmeProfileEditRequestDto
     */
    raProfileUuid?: string;
    /**
     * Retry interval for the Orders
     * @type {number}
     * @memberof AcmeProfileEditRequestDto
     */
    retryInterval?: number;
    /**
     * Disable new Orders due to change in Terms of Service
     * @type {boolean}
     * @memberof AcmeProfileEditRequestDto
     */
    termsOfServiceChangeDisable?: boolean;
    /**
     * Changes of Terms of Service URL
     * @type {string}
     * @memberof AcmeProfileEditRequestDto
     */
    termsOfServiceChangeUrl?: string;
    /**
     * Order Validity
     * @type {number}
     * @memberof AcmeProfileEditRequestDto
     */
    validity?: number;
    /**
     * List of Attributes to issue Certificate
     * @type {Array<RequestAttribute>}
     * @memberof AcmeProfileEditRequestDto
     */
    issueCertificateAttributes: Array<RequestAttribute>;
    /**
     * List of Attributes to revoke Certificate
     * @type {Array<RequestAttribute>}
     * @memberof AcmeProfileEditRequestDto
     */
    revokeCertificateAttributes: Array<RequestAttribute>;
    /**
     * Require contact information for new Account
     * @type {boolean}
     * @memberof AcmeProfileEditRequestDto
     */
    requireContact?: boolean;
    /**
     * Require new Account to agree on Terms of Service
     * @type {boolean}
     * @memberof AcmeProfileEditRequestDto
     */
    requireTermsOfService?: boolean;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof AcmeProfileEditRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * Associations to set for certificates issued by the protocol
     * @type {ProtocolCertificateAssociationsRequestDto}
     * @memberof AcmeProfileEditRequestDto
     */
    certificateAssociations?: ProtocolCertificateAssociationsRequestDto;
    /**
     * UUIDs of the secrets holding the External Account Binding HMAC keys accepted by this ACME Profile. Each secret\'s UUID is the kid an ACME client binds a new Account with, and its content is the base64url-encoded key. A non-empty list makes External Account Binding mandatory - the directory meta then advertises externalAccountRequired. Omitting the property keeps the profile\'s current secrets; send an empty array to clear them and leave Account registration open.
     * @type {Array<string>}
     * @memberof AcmeProfileEditRequestDto
     */
    eabSecretUuids?: Array<string>;
    /**
     * Identifiers an account may obtain from this profile without proving control of them. An order whose identifiers are all covered is ready at creation and carries no challenges. Omitting the property keeps the profile\'s current entries; send an empty array to clear them.
     * @type {Array<AcmePreauthorizedIdentifierDto>}
     * @memberof AcmeProfileEditRequestDto
     */
    preauthorizedIdentifiers?: Array<AcmePreauthorizedIdentifierDto>;
    /**
     * What happens to an ordered identifier the pre-authorization policy does not cover. \'preauthorizedOrChallenge\', the default, sends it through the usual http-01 and dns-01 flow. \'preauthorizedOnly\' refuses the order, and needs at least one pre-authorized identifier - to stop a profile accepting orders at all, disable new orders instead. Omitting the property keeps the profile\'s current mode.
     * @type {AcmeIdentifierAuthorizationMode}
     * @memberof AcmeProfileEditRequestDto
     */
    identifierAuthorizationMode?: AcmeIdentifierAuthorizationMode;
}
