// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AcmeIdentifierMatchType, AcmeIdentifierType } from './';

/**
 * An identifier an ACME account may obtain from this profile without proving control of it. An order whose identifiers are all covered gets its authorizations created valid, so no http-01 or dns-01 challenge is issued for them.
 * @export
 * @interface AcmePreauthorizedIdentifierDto
 */
export interface AcmePreauthorizedIdentifierDto {
    /**
     * Which kind of ordered identifier this entry can cover. An entry covers its own type and no other, so a dotted value listed as \'ip\' never pre-authorizes the DNS name that reads the same.
     * @type {AcmeIdentifierType}
     * @memberof AcmePreauthorizedIdentifierDto
     */
    type: AcmeIdentifierType;
    /**
     * The identifier value: a DNS name, or an IP address for an RFC 8738 ip identifier.
     * @type {string}
     * @memberof AcmePreauthorizedIdentifierDto
     */
    value: string;
    /**
     * How the value is compared with an ordered identifier. \'exact\' covers that identifier only. \'subdomain\' covers descendants of the name at any depth but not the name itself, so covering both takes two entries; it applies to DNS names, an IP address always being matched exactly. DNS comparison is case-insensitive, IP comparison is by octets.
     * @type {AcmeIdentifierMatchType}
     * @memberof AcmePreauthorizedIdentifierDto
     */
    matchType: AcmeIdentifierMatchType;
    /**
     * Whether the wildcard identifier of this entry may also be pre-authorized. It sits on the entry rather than the profile, so allowing \'*.apps.example.com\' is a decision about that pattern rather than a switch over every listed name. A wildcard is covered only when everything it stands for is already inside this entry\'s scope.
     * @type {boolean}
     * @memberof AcmePreauthorizedIdentifierDto
     */
    allowWildcard?: boolean;
}
