// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * A freshly generated External Account Binding HMAC key. The platform does not store it - store it in a secret and register that secret\'s UUID on an ACME Profile to put the key into use.
 * @export
 * @interface AcmeEabKeyDto
 */
export interface AcmeEabKeyDto {
    /**
     * Base64url-encoded HMAC key, 256 bits of randomness. This is the value an ACME client MACs its External Account Binding with, and the value to store as the secret\'s content.
     * @type {string}
     * @memberof AcmeEabKeyDto
     */
    key: string;
}
