// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface AppInfoDto
 */
export interface AppInfoDto {
    /**
     * Platform Application Name
     * @type {string}
     * @memberof AppInfoDto
     */
    name: string;
    /**
     * Platform Core Version
     * @type {string}
     * @memberof AppInfoDto
     */
    version: string;
}
