// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.14.2-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ApprovalProfileForVersionDto
 */
export interface ApprovalProfileForVersionDto {
    /**
     * @type {number}
     * @memberof ApprovalProfileForVersionDto
     */
    version?: number;
}
