// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum AttributeResource {
    Certificates = 'certificates',
    Credentials = 'credentials',
    Authorities = 'authorities',
    Entities = 'entities',
    Locations = 'locations',
    Secrets = 'secrets',
}
