// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { OAuth2ProviderSettingsDto } from './';

/**
 * @export
 * @interface AuthenticationSettingsUpdateDto
 */
export interface AuthenticationSettingsUpdateDto {
    /**
     * Disable using localhost user for requests from localhost
     * @type {boolean}
     * @memberof AuthenticationSettingsUpdateDto
     */
    disableLocalhostUser: boolean;
    /**
     * @type {Array<OAuth2ProviderSettingsDto>}
     * @memberof AuthenticationSettingsUpdateDto
     */
    oauth2Providers?: Array<OAuth2ProviderSettingsDto>;
}
