// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.16.1
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Boolean attribute content to store true/false values
 * @export
 * @interface BooleanAttributeContent
 */
export interface BooleanAttributeContent {
    /**
     * Content Reference
     * @type {string}
     * @memberof BooleanAttributeContent
     */
    reference?: string;
    /**
     * Boolean attribute value
     * @type {boolean}
     * @memberof BooleanAttributeContent
     */
    data: boolean;
}
