// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CbomSyncSkipState } from './';

/**
 * @export
 * @interface CbomSyncSkipDto
 */
export interface CbomSyncSkipDto {
    /**
     * UUID of the record
     * @type {string}
     * @memberof CbomSyncSkipDto
     */
    uuid: string;
    /**
     * Serial number (URN) of the CBOM the repository lists
     * @type {string}
     * @memberof CbomSyncSkipDto
     */
    serialNumber: string;
    /**
     * Version of the CBOM the repository lists
     * @type {number}
     * @memberof CbomSyncSkipDto
     */
    version: number;
    /**
     * Whether the next sync runs still try the entry, or the retry budget is spent
     * @type {CbomSyncSkipState}
     * @memberof CbomSyncSkipDto
     */
    state: CbomSyncSkipState;
    /**
     * Failed attempts charged to the entry\'s current retry budget, the one that first failed included. The budget is spent when this reaches cbomSyncSkippedRetryRuns + 1. An operator\'s retry gives the entry a new budget and returns this to 0, while firstSkippedAt, lastAttemptAt and reason keep the record of what has happened so far -- so a count of 0 beside an earlier first failure means a retry was asked for and no run has tried the entry since
     * @type {number}
     * @memberof CbomSyncSkipDto
     */
    attempts: number;
    /**
     * When the entry first failed
     * @type {string}
     * @memberof CbomSyncSkipDto
     */
    firstSkippedAt: string;
    /**
     * When the entry was last tried
     * @type {string}
     * @memberof CbomSyncSkipDto
     */
    lastAttemptAt: string;
    /**
     * Why the last attempt failed, in words meant for an operator; never a raw driver or parser message
     * @type {string}
     * @memberof CbomSyncSkipDto
     */
    reason: string;
    /**
     * Number of algorithms the repository listing reported for the entry
     * @type {number}
     * @memberof CbomSyncSkipDto
     */
    algorithms: number;
    /**
     * Number of certificates the repository listing reported for the entry
     * @type {number}
     * @memberof CbomSyncSkipDto
     */
    certificates: number;
    /**
     * Number of protocols the repository listing reported for the entry
     * @type {number}
     * @memberof CbomSyncSkipDto
     */
    protocols: number;
    /**
     * Number of crypto material items the repository listing reported for the entry
     * @type {number}
     * @memberof CbomSyncSkipDto
     */
    cryptoMaterial: number;
    /**
     * Total number of assets the repository listing reported for the entry
     * @type {number}
     * @memberof CbomSyncSkipDto
     */
    totalAssets: number;
}
