// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ExtensionValueEncoding } from './';

/**
 * @export
 * @interface CertificateExtensionOidPropertiesDto
 */
export interface CertificateExtensionOidPropertiesDto {
    /**
     * Whether this extension should be marked critical by default when placed in a certificate
     * @type {boolean}
     * @memberof CertificateExtensionOidPropertiesDto
     */
    defaultCritical: boolean;
    /**
     * ASN.1 encoding used to encode the attribute string value into the extension DER value
     * @type {ExtensionValueEncoding}
     * @memberof CertificateExtensionOidPropertiesDto
     */
    valueEncoding: ExtensionValueEncoding;
    /**
     * Inline JSON Schema (draft 2020-12) describing the shape of the extension\'s JSON value; only applicable when valueEncoding is DER, where the value is authored as a structural ASN.1 JSON tree
     * @type {string}
     * @memberof CertificateExtensionOidPropertiesDto
     */
    valueSchema?: string;
}
