// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * @export
 * @interface CertificateUpdateObjectsDto
 */
export interface CertificateUpdateObjectsDto {
    /**
     * Certificate Groups UUIDs (set to empty list to remove certificate from all groups)
     * @type {Array<string>}
     * @memberof CertificateUpdateObjectsDto
     */
    groupUuids?: Array<string>;
    /**
     * Certificate owner user UUID (set to empty string to remove owner of certificate)
     * @type {string}
     * @memberof CertificateUpdateObjectsDto
     */
    ownerUuid?: string;
    /**
     * RA Profile UUID (set to empty string to remove certificate from RA profile)
     * @type {string}
     * @memberof CertificateUpdateObjectsDto
     */
    raProfileUuid?: string;
    /**
     * Identify-operation dynamic attributes, as listed by GET /v1/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/identify for the target RA profile. Used only when raProfileUuid assigns a new RA profile, which identifies the certificate at its authority. Optional — an authority that offers no identify schema needs none.
     * @type {Array<RequestAttribute>}
     * @memberof CertificateUpdateObjectsDto
     */
    attributes?: Array<RequestAttribute>;
    /**
     * Mark CA certificate as trusted
     * @type {boolean}
     * @memberof CertificateUpdateObjectsDto
     */
    trustedCa?: boolean;
}
