// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ExtensionValueEncoding } from './';

/**
 * How a certificate extension\'s value is carried. The valueSchema field is named for the job rather than the notation: a value\'s shape is described by an ASN.1 module, which is what X.697 calls a schema when it uses ASN.1 as one for JSON.
 * @export
 * @interface CertificateExtensionOidPropertiesDto
 */
export interface CertificateExtensionOidPropertiesDto {
    /**
     * Whether this extension should be marked critical by default when placed in a certificate
     * @type {boolean}
     * @memberof CertificateExtensionOidPropertiesDto
     */
    defaultCritical: boolean;
    /**
     * ASN.1 encoding used to encode the attribute string value into the extension DER value
     * @type {ExtensionValueEncoding}
     * @memberof CertificateExtensionOidPropertiesDto
     */
    valueEncoding: ExtensionValueEncoding;
    /**
     * ASN.1 module defining the extension\'s value type, in the subset of X.680 the platform supports; only applicable when valueEncoding is DER. Base64-encoded DER is accepted as the value whether or not a module is registered; a module additionally admits values written as JSON naming the type\'s members, in the JSON Encoding Rules of X.697.
     * @type {string}
     * @memberof CertificateExtensionOidPropertiesDto
     */
    valueSchema?: string;
}
