// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateEntryKeyDestinationDto } from './';

/**
 * An entry to import and the destination of its key material
 * @export
 * @interface CertificateImportEntryDto
 */
export interface CertificateImportEntryDto {
    /**
     * Reference of the entry to import. Read the file first to learn it, or compute it from content already held.  The lowercase hex SHA-256 of the entry\'s DER: of the certificate for a certificate, of the `SubjectPublicKeyInfo` for a key pair or private key, of the key as the file holds it for a secret key or a key of an algorithm the platform does not support, and of the request for a certificate request.
     * @type {string}
     * @memberof CertificateImportEntryDto
     */
    entryReference: string;
    /**
     * Where this entry\'s key material is stored. Required when the entry carries key material, and refused for an entry that carries only a certificate.
     * @type {CertificateEntryKeyDestinationDto}
     * @memberof CertificateImportEntryDto
     */
    keyDestination?: CertificateEntryKeyDestinationDto;
}
