// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ImportOutcome, InspectedEntryKind } from './';

/**
 * Outcome of importing one entry
 * @export
 * @interface CertificateImportResultDto
 */
export interface CertificateImportResultDto {
    /**
     * Reference of the entry this outcome belongs to
     * @type {string}
     * @memberof CertificateImportResultDto
     */
    entryReference: string;
    /**
     * What the entry turned out to be
     * @type {InspectedEntryKind}
     * @memberof CertificateImportResultDto
     */
    kind: InspectedEntryKind;
    /**
     * Whether the entry\'s objects are in the inventory after the call
     * @type {boolean}
     * @memberof CertificateImportResultDto
     */
    imported: boolean;
    /**
     * What became of the certificate, when the entry carried one
     * @type {ImportOutcome}
     * @memberof CertificateImportResultDto
     */
    certificateOutcome?: ImportOutcome;
    /**
     * UUID of the entry\'s certificate, withheld when the caller may not see it in detail
     * @type {string}
     * @memberof CertificateImportResultDto
     */
    certificateUuid?: string;
    /**
     * What became of the key, when the entry carried key material
     * @type {ImportOutcome}
     * @memberof CertificateImportResultDto
     */
    keyOutcome?: ImportOutcome;
    /**
     * UUID of the entry\'s key, withheld for a key already in the inventory that the caller may not see in detail
     * @type {string}
     * @memberof CertificateImportResultDto
     */
    keyUuid?: string;
    /**
     * Why this entry was not imported, when it was not
     * @type {string}
     * @memberof CertificateImportResultDto
     */
    message?: string;
}
