// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ClientCertificateDataResponseDto
 */
export interface ClientCertificateDataResponseDto {
    /**
     * Base64-encoded signed certificate. The issuance operations complete asynchronously and leave this empty; register leaves it empty too unless the authority returns certificate data synchronously. Retrieve the signed certificate from the certificate detail once the certificate reaches the ISSUED state.
     * @type {string}
     * @memberof ClientCertificateDataResponseDto
     */
    certificateData?: string;
    /**
     * UUID of Certificate
     * @type {string}
     * @memberof ClientCertificateDataResponseDto
     */
    uuid: string;
    /**
     * Request-attribute policy warnings raised while validating an externally supplied CSR under lenient request validation. Empty under strict, where a violation is rejected with 422 instead of accepted with warnings.
     * @type {Array<string>}
     * @memberof ClientCertificateDataResponseDto
     */
    requestAttributeWarnings?: Array<string>;
}
