// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateRequestFormat, RequestAttribute } from './';

/**
 * @export
 * @interface ClientCertificateRenewRequestDto
 */
export interface ClientCertificateRenewRequestDto {
    /**
     * True to replace renewed certificate in the associated locations
     * @type {boolean}
     * @memberof ClientCertificateRenewRequestDto
     */
    replaceInLocations?: boolean;
    /**
     * Certificate signing request encoded as Base64 string. If not provided, Existing CSR will be used
     * @type {string}
     * @memberof ClientCertificateRenewRequestDto
     */
    request?: string;
    /**
     * Certificate signing request format
     * @type {CertificateRequestFormat}
     * @memberof ClientCertificateRenewRequestDto
     */
    format?: CertificateRequestFormat;
    /**
     * Renew-specific dynamic attributes, as listed by GET /v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/renew. Optional — an authority that offers no renew schema needs none.
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRenewRequestDto
     */
    attributes?: Array<RequestAttribute>;
    /**
     * One-time authorization secret for renewing a certificate that has an active registration. Write-only; ignored for certificates without one.
     * @type {string}
     * @memberof ClientCertificateRenewRequestDto
     */
    authorizationSecret?: string;
}
