// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateRequestFormat, RequestAttribute } from './';

/**
 * @export
 * @interface ClientCertificateRekeyRequestDto
 */
export interface ClientCertificateRekeyRequestDto {
    /**
     * True to replace renewed certificate in the associated locations
     * @type {boolean}
     * @memberof ClientCertificateRekeyRequestDto
     */
    replaceInLocations?: boolean;
    /**
     * Certificate signing request encoded as Base64 string. If not provided, CSR attributes will be used
     * @type {string}
     * @memberof ClientCertificateRekeyRequestDto
     */
    request?: string;
    /**
     * Certificate signing request format
     * @type {CertificateRequestFormat}
     * @memberof ClientCertificateRekeyRequestDto
     */
    format?: CertificateRequestFormat;
    /**
     * Key UUID
     * @type {string}
     * @memberof ClientCertificateRekeyRequestDto
     */
    keyUuid?: string;
    /**
     * Token Profile UUID
     * @type {string}
     * @memberof ClientCertificateRekeyRequestDto
     */
    tokenProfileUuid?: string;
    /**
     * Alternative Key UUID
     * @type {string}
     * @memberof ClientCertificateRekeyRequestDto
     */
    altKeyUuid?: string;
    /**
     * Token Profile UUID for the alternative key
     * @type {string}
     * @memberof ClientCertificateRekeyRequestDto
     */
    altTokenProfileUuid?: string;
    /**
     * Signature Attributes. If not provided, existing attributes will be used to generate the new CSR
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRekeyRequestDto
     */
    signatureAttributes?: Array<RequestAttribute>;
    /**
     * Alternative Signature Attributes. If not provided, existing alternative attributes will be used to generate the new CSR
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRekeyRequestDto
     */
    altSignatureAttributes?: Array<RequestAttribute>;
    /**
     * Rekey dynamic attributes. Rekey is a renew at the authority — there is no separate rekey operation on the connector contract — so this uses the renew schema, as listed by GET /v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/renew. Distinct from signatureAttributes/altSignatureAttributes, which configure CSR signing, not the CA operation.
     * @type {Array<RequestAttribute>}
     * @memberof ClientCertificateRekeyRequestDto
     */
    attributes?: Array<RequestAttribute>;
    /**
     * One-time authorization secret for rekeying a certificate that has an active registration. Write-only; ignored for certificates without one.
     * @type {string}
     * @memberof ClientCertificateRekeyRequestDto
     */
    authorizationSecret?: string;
}
