// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ProtocolChallengeSource, SimplifiedRaProfileDto } from './';

/**
 * @export
 * @interface CmpProfileDto
 */
export interface CmpProfileDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof CmpProfileDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof CmpProfileDto
     */
    name: string;
    /**
     * Enabled flag - true = enabled; false = disabled
     * @type {boolean}
     * @memberof CmpProfileDto
     */
    enabled: boolean;
    /**
     * Variant of the CMP Profile
     * @type {string}
     * @memberof CmpProfileDto
     */
    variant: CmpProfileDtoVariantEnum;
    /**
     * CMP Profile description
     * @type {string}
     * @memberof CmpProfileDto
     */
    description?: string;
    /**
     * RA Profile associated with the CMP Profile
     * @type {SimplifiedRaProfileDto}
     * @memberof CmpProfileDto
     */
    raProfile?: SimplifiedRaProfileDto;
    /**
     * CMP URL
     * @type {string}
     * @memberof CmpProfileDto
     */
    cmpUrl?: string;
    /**
     * Source of the credential for MAC-protected requests
     * @type {ProtocolChallengeSource}
     * @memberof CmpProfileDto
     */
    challengeSource: ProtocolChallengeSource;
}

/**
 * @export
 * @enum {string}
 */
export enum CmpProfileDtoVariantEnum {
    V2 = 'v2',
    V23gpp = 'v2_3gpp',
    V3 = 'v3',
}
