// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Request to post a comment or a reply on an object. Author identity and creation timestamp are populated by the server from the authenticated principal.
 * @export
 * @interface CommentCreateRequestDto
 */
export interface CommentCreateRequestDto {
    /**
     * Comment body as verbatim Markdown source
     * @type {string}
     * @memberof CommentCreateRequestDto
     */
    body: string;
    /**
     * UUID of the thread root this comment replies to. Threads are one level deep: the referenced comment must be a thread root on the same object.
     * @type {string}
     * @memberof CommentCreateRequestDto
     */
    parentUuid?: string;
}
