// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NameAndUuidDto, Resource } from './';

/**
 * A comment on an object. Thread roots carry resolution state and a reply count; replies carry neither.
 * @export
 * @interface CommentDto
 */
export interface CommentDto {
    /**
     * Comment UUID
     * @type {string}
     * @memberof CommentDto
     */
    uuid: string;
    /**
     * Host resource the commented object belongs to
     * @type {Resource}
     * @memberof CommentDto
     */
    resource: Resource;
    /**
     * UUID of the commented object
     * @type {string}
     * @memberof CommentDto
     */
    objectUuid: string;
    /**
     * UUID and username of the author; server-populated
     * @type {NameAndUuidDto}
     * @memberof CommentDto
     */
    author: NameAndUuidDto;
    /**
     * Creation timestamp; server-populated
     * @type {string}
     * @memberof CommentDto
     */
    createdAt: string;
    /**
     * Comment body as verbatim Markdown source
     * @type {string}
     * @memberof CommentDto
     */
    body: string;
    /**
     * Whether the thread is resolved; thread roots only
     * @type {boolean}
     * @memberof CommentDto
     */
    resolved?: boolean;
    /**
     * UUID and username of the resolving user; resolved thread roots only
     * @type {NameAndUuidDto}
     * @memberof CommentDto
     */
    resolvedBy?: NameAndUuidDto;
    /**
     * Resolution timestamp; resolved thread roots only
     * @type {string}
     * @memberof CommentDto
     */
    resolvedAt?: string;
    /**
     * Number of replies in the thread; thread roots only. The replies themselves are paged separately.
     * @type {number}
     * @memberof CommentDto
     */
    replyCount?: number;
}
