// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CommentDto } from './';

/**
 * @export
 * @interface CommentResponseDto
 */
export interface CommentResponseDto {
    /**
     * Number of entries per page
     * @type {number}
     * @memberof CommentResponseDto
     */
    itemsPerPage: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof CommentResponseDto
     */
    pageNumber: number;
    /**
     * Number of pages available
     * @type {number}
     * @memberof CommentResponseDto
     */
    totalPages: number;
    /**
     * Number of items available
     * @type {number}
     * @memberof CommentResponseDto
     */
    totalItems: number;
    /**
     * Comments on the requested page: thread roots for the object listing, replies for the thread listing
     * @type {Array<CommentDto>}
     * @memberof CommentResponseDto
     */
    comments: Array<CommentDto>;
}
