// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { KeyCompromiseReason } from './';

/**
 * @export
 * @interface CompromiseKeyRequestDto
 */
export interface CompromiseKeyRequestDto {
    /**
     * Reason for marking the key items as compromised
     * @type {KeyCompromiseReason}
     * @memberof CompromiseKeyRequestDto
     */
    reason: KeyCompromiseReason;
    /**
     * UUIDs of the key items to mark as compromised. If omitted or empty, all items in the key are marked as compromised.
     * @type {Array<string>}
     * @memberof CompromiseKeyRequestDto
     */
    uuids?: Array<string>;
}
