// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ComplianceGroupRequestDto
 */
export interface ComplianceGroupRequestDto {
    /**
     * UUID of the Compliance Provider
     * @type {string}
     * @memberof ComplianceGroupRequestDto
     */
    connectorUuid: string;
    /**
     * Kind of the Compliance Provider
     * @type {string}
     * @memberof ComplianceGroupRequestDto
     */
    kind: string;
    /**
     * UUID of the group
     * @type {string}
     * @memberof ComplianceGroupRequestDto
     */
    groupUuid: string;
}
