// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ComplianceGroupsResponseDto
 */
export interface ComplianceGroupsResponseDto {
    /**
     * UUID of the group
     * @type {string}
     * @memberof ComplianceGroupsResponseDto
     */
    uuid: string;
    /**
     * Name of the group
     * @type {string}
     * @memberof ComplianceGroupsResponseDto
     */
    name: string;
    /**
     * Description of the group
     * @type {string}
     * @memberof ComplianceGroupsResponseDto
     */
    description?: string;
}
