// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum ConnectorInterface {
    Info = 'info',
    Health = 'health',
    Metrics = 'metrics',
    Attributes = 'attributes',
    Authority = 'authority',
    Discovery = 'discovery',
    Entity = 'entity',
    Compliance = 'compliance',
    Cryptography = 'cryptography',
    Notification = 'notification',
    Secret = 'secret',
    SignatureFormatting = 'signatureFormatting',
    CadesFormatting = 'cadesFormatting',
    JadesFormatting = 'jadesFormatting',
    PadesFormatting = 'padesFormatting',
    XadesFormatting = 'xadesFormatting',
}
