// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ConnectorInterface, FeatureFlag } from './';

/**
 * @export
 * @interface ConnectorInterfaceInfo
 */
export interface ConnectorInterfaceInfo {
    /**
     * Code of the implemented connector interface
     * @type {ConnectorInterface}
     * @memberof ConnectorInterfaceInfo
     */
    code: ConnectorInterface;
    /**
     * Version of the implemented connector interface
     * @type {string}
     * @memberof ConnectorInterfaceInfo
     */
    version: string;
    /**
     * Features supported by the connector interface
     * @type {Array<FeatureFlag>}
     * @memberof ConnectorInterfaceInfo
     */
    features?: Array<FeatureFlag>;
}
