// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NameAndUuidDto, ResponseAttribute, SignatureFamily, SignatureLevel, SigningWorkflowType, TimestampSourceDto } from './';

/**
 * Content signing workflow configuration. The validation material that LONG_TERM and ARCHIVAL embed is fetched by the Signature Formatting Provider and is not configured here.
 * @export
 * @interface ContentSigningWorkflowDto
 */
export interface ContentSigningWorkflowDto {
    /**
     * Signing workflow type
     * @type {SigningWorkflowType}
     * @memberof ContentSigningWorkflowDto
     */
    type: SigningWorkflowType;
    /**
     * Signature Formatting Provider that constructs the data-to-be-signed (DTBS) for Content signing. Present only when ILM-managed signing is used; null for delegated signing.
     * @type {NameAndUuidDto}
     * @memberof ContentSigningWorkflowDto
     */
    signatureFormattingConnector?: NameAndUuidDto;
    /**
     * Attributes configured on the Signature Formatting Provider that control DTBS construction for the content signing workflow. Applicable only when ILM-managed signing is used.
     * @type {Array<ResponseAttribute>}
     * @memberof ContentSigningWorkflowDto
     */
    signatureFormattingConnectorAttributes?: Array<ResponseAttribute>;
    /**
     * Signature family this profile produces. Present only when ILM-managed signing is used; null for delegated signing.
     * @type {SignatureFamily}
     * @memberof ContentSigningWorkflowDto
     */
    family?: SignatureFamily;
    /**
     * Highest signature level a request may ask for. A request asking for more is rejected. Present only when ILM-managed signing is used; null for delegated signing.
     * @type {SignatureLevel}
     * @memberof ContentSigningWorkflowDto
     */
    maxLevel?: SignatureLevel;
    /**
     * Source of the timestamps embedded at level TIMESTAMPED and above. Set when maxLevel is TIMESTAMPED or higher.
     * @type {TimestampSourceDto}
     * @memberof ContentSigningWorkflowDto
     */
    timestampSource?: TimestampSourceDto;
    /**
     * Largest document accepted for signing, in bytes. Enforced when an ILM-managed signing request arrives. Null when no profile-level cap applies.
     * @type {number}
     * @memberof ContentSigningWorkflowDto
     */
    documentSizeCap?: number;
    /**
     * Demand the nonRepudiation key-usage bit specifically, for commitment-grade profiles. Applies to ILM-managed signing only; delegated profile gets always false.
     * @type {boolean}
     * @memberof ContentSigningWorkflowDto
     */
    requireNonRepudiation?: boolean;
    /**
     * Extended key usage OIDs the signing certificate must all carry, in dot notation (1.3.6.1.5.5.7.3.36 is RFC 9336 id-kp-documentSigning). An empty set accepts any extended key usage. Applies to ILM-managed signing only.
     * @type {Array<string>}
     * @memberof ContentSigningWorkflowDto
     */
    requiredExtendedKeyUsageOids?: Array<string>;
}
