// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute, SignatureFamily, SignatureLevel, SigningWorkflowType, TimestampSourceRequestDto } from './';

/**
 * Content signing workflow configuration request. The validation material that LONG_TERM and ARCHIVAL embed is fetched by the Signature Formatting Provider and needs no configuration here.
 * @export
 * @interface ContentSigningWorkflowRequestDto
 */
export interface ContentSigningWorkflowRequestDto {
    /**
     * Signing workflow type
     * @type {SigningWorkflowType}
     * @memberof ContentSigningWorkflowRequestDto
     */
    type: SigningWorkflowType;
    /**
     * UUID of the Signature Formatting Provider that constructs the data-to-be-signed (DTBS) for Content signing. Required for ILM-managed signing; must be omitted for delegated signing.
     * @type {string}
     * @memberof ContentSigningWorkflowRequestDto
     */
    signatureFormattingConnectorUuid?: string;
    /**
     * Attributes for the Signature Formatting Provider that control DTBS construction for the content signing workflow. Must be omitted for delegated signing.
     * @type {Array<RequestAttribute>}
     * @memberof ContentSigningWorkflowRequestDto
     */
    signatureFormattingConnectorAttributes?: Array<RequestAttribute>;
    /**
     * Signature family this profile produces. Required for ILM-managed signing; must be omitted for delegated signing.
     * @type {SignatureFamily}
     * @memberof ContentSigningWorkflowRequestDto
     */
    family?: SignatureFamily;
    /**
     * Highest signature level a request may ask for. A request asking for more is rejected. Required for ILM-managed signing; must be omitted for delegated signing.
     * @type {SignatureLevel}
     * @memberof ContentSigningWorkflowRequestDto
     */
    maxLevel?: SignatureLevel;
    /**
     * Source of the timestamps embedded at level TIMESTAMPED and above. Required when maxLevel is TIMESTAMPED or higher, and must be omitted when maxLevel is SIGNED, which embeds no timestamp. Must be omitted for delegated signing.
     * @type {TimestampSourceRequestDto}
     * @memberof ContentSigningWorkflowRequestDto
     */
    timestampSource?: TimestampSourceRequestDto;
    /**
     * Largest document accepted for signing, in bytes. Enforced when an ILM-managed signing request arrives. When omitted, no profile-level cap applies.
     * @type {number}
     * @memberof ContentSigningWorkflowRequestDto
     */
    documentSizeCap?: number;
    /**
     * Demand the nonRepudiation key-usage bit specifically, for commitment-grade profiles. Applies to ILM-managed signing only. For delegated signing, omit it or send false; an echoed false from a response is accepted, true is rejected.
     * @type {boolean}
     * @memberof ContentSigningWorkflowRequestDto
     */
    requireNonRepudiation?: boolean;
    /**
     * Extended key usage OIDs the signing certificate must all carry, in dot notation (1.3.6.1.5.5.7.3.36 is RFC 9336 id-kp-documentSigning). An empty set accepts any extended key usage. Applies to ILM-managed signing only; for delegated signing send nothing or an empty set.
     * @type {Array<string>}
     * @memberof ContentSigningWorkflowRequestDto
     */
    requiredExtendedKeyUsageOids?: Array<string>;
}
