// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CryptographicAssetEvidenceDto
 */
export interface CryptographicAssetEvidenceDto {
    /**
     * Where the occurrence was found: a file path, URL or other locator from the source document, sanitized before storage (URI user information stripped, query and fragment dropped) and capped at 1024 characters
     * @type {string}
     * @memberof CryptographicAssetEvidenceDto
     */
    location: string;
    /**
     * Line number within the location
     * @type {number}
     * @memberof CryptographicAssetEvidenceDto
     */
    line?: number;
    /**
     * Offset within the location
     * @type {number}
     * @memberof CryptographicAssetEvidenceDto
     */
    offset?: number;
    /**
     * Symbol recorded at the occurrence
     * @type {string}
     * @memberof CryptographicAssetEvidenceDto
     */
    symbol?: string;
}
