// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    CryptographicAssetNormalizedFieldsDto,
    CryptographicAssetOidDto,
    CryptographicAssetSourceDto,
    CryptographicAssetType,
    CryptographicAssetVerdictDto,
    PqcVerdict,
} from './';

/**
 * @export
 * @interface CryptographicAssetDetailDto
 */
export interface CryptographicAssetDetailDto {
    /**
     * UUID of the inventory asset
     * @type {string}
     * @memberof CryptographicAssetDetailDto
     */
    uuid: string;
    /**
     * Normalized display name of the asset
     * @type {string}
     * @memberof CryptographicAssetDetailDto
     */
    name: string;
    /**
     * Type of the asset
     * @type {CryptographicAssetType}
     * @memberof CryptographicAssetDetailDto
     */
    type: CryptographicAssetType;
    /**
     * Post-quantum readiness verdict computed by the platform rule set
     * @type {PqcVerdict}
     * @memberof CryptographicAssetDetailDto
     */
    pqcVerdict: PqcVerdict;
    /**
     * Number of CBOM documents that reference this asset
     * @type {number}
     * @memberof CryptographicAssetDetailDto
     */
    sourceCbomCount: number;
    /**
     * Total number of occurrence evidence entries recorded across all source CBOMs
     * @type {number}
     * @memberof CryptographicAssetDetailDto
     */
    occurrenceCount: number;
    /**
     * True when sources make contradicting claims about this asset that are quarantined pending reconciliation
     * @type {boolean}
     * @memberof CryptographicAssetDetailDto
     */
    quarantined: boolean;
    /**
     * Provenance of the asset\'s PQC verdict
     * @type {CryptographicAssetVerdictDto}
     * @memberof CryptographicAssetDetailDto
     */
    verdict: CryptographicAssetVerdictDto;
    /**
     * Normalized filterable properties derived for the asset; absent when nothing is derivable
     * @type {CryptographicAssetNormalizedFieldsDto}
     * @memberof CryptographicAssetDetailDto
     */
    normalizedFields?: CryptographicAssetNormalizedFieldsDto;
    /**
     * The representative payload: one source\'s payload served verbatim, elected deterministically (richest payload first, ties broken on a canonical form of the payload) and never merged across sources. Absent when no source carries a payload
     * @type {{ [key: string]: any; }}
     * @memberof CryptographicAssetDetailDto
     */
    electedPayload?: { [key: string]: any };
    /**
     * Source CBOM documents referencing this asset, with per-source payload and evidence
     * @type {Array<CryptographicAssetSourceDto>}
     * @memberof CryptographicAssetDetailDto
     */
    sources: Array<CryptographicAssetSourceDto>;
    /**
     * Object identifiers producers attached to this asset; may be empty
     * @type {Array<CryptographicAssetOidDto>}
     * @memberof CryptographicAssetDetailDto
     */
    oids: Array<CryptographicAssetOidDto>;
}
