// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Coverage of the cryptographic asset sync across stored CBOM documents
 * @export
 * @interface CryptographicAssetSyncCompletenessDto
 */
export interface CryptographicAssetSyncCompletenessDto {
    /**
     * CBOM document count by asset sync state. Keys are CbomAssetSyncState codes; every state is present, with 0 when none
     * @type {{ [key: string]: number; }}
     * @memberof CryptographicAssetSyncCompletenessDto
     */
    cbomStatBySyncState?: { [key: string]: number };
    /**
     * The most recent time any record successfully reached the synced state; absent until the first record does
     * @type {string}
     * @memberof CryptographicAssetSyncCompletenessDto
     */
    lastCompletedSyncAt?: string;
}
