// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Type of an asset in the cryptographic asset inventory: the CycloneDX cryptoProperties.assetType vocabulary. An asset that declares none of these types is served with no type
 * @export
 * @enum {string}
 */
export enum CryptographicAssetType {
    Algorithm = 'algorithm',
    Certificate = 'certificate',
    Protocol = 'protocol',
    RelatedCryptoMaterial = 'related-crypto-material',
    Unroutable = 'unroutable',
}
