// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CryptographicAssetVerdictDto
 */
export interface CryptographicAssetVerdictDto {
    /**
     * Version of the platform rule set that produced the verdict
     * @type {number}
     * @memberof CryptographicAssetVerdictDto
     */
    ruleSetVersion: number;
    /**
     * The rule that decided the verdict; absent when no rule matched and the verdict is the rule set\'s default
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    ruleId?: string;
    /**
     * The deciding rule\'s finding; absent when no rule matched
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    reason?: string;
    /**
     * Values of the asset fields the deciding rule evaluated, recorded at decision time
     * @type {{ [key: string]: any; }}
     * @memberof CryptographicAssetVerdictDto
     */
    evaluatedFields?: { [key: string]: any };
    /**
     * When the current verdict value was decided
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    decidedAt: string;
    /**
     * When the verdict was last evaluated; a re-evaluation that confirms the verdict advances this and not decidedAt
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    evaluatedAt: string;
}
