// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CryptographicAssetEvidenceDto } from './';

/**
 * @export
 * @interface CryptographicAssetSourceDto
 */
export interface CryptographicAssetSourceDto {
    /**
     * UUID of the source CBOM record
     * @type {string}
     * @memberof CryptographicAssetSourceDto
     */
    cbomUuid: string;
    /**
     * Serial number (URN) of the source CBOM
     * @type {string}
     * @memberof CryptographicAssetSourceDto
     */
    serialNumber: string;
    /**
     * Version of the source CBOM
     * @type {number}
     * @memberof CryptographicAssetSourceDto
     */
    version: number;
    /**
     * Number of occurrences this source recorded for the asset, counted before the served evidence list is capped
     * @type {number}
     * @memberof CryptographicAssetSourceDto
     */
    occurrenceCount: number;
    /**
     * Tool or scan that produced the source CBOM (e.g.: CBOM-Lens)
     * @type {string}
     * @memberof CryptographicAssetSourceDto
     */
    source: string;
    /**
     * Cryptographic properties of the component as this source declared them. Keys follow the source document\'s CycloneDX version and are always source-derived — the platform adds no keys of its own. Values classified as secret material are stored and served as the redaction envelope {\"redacted\": true, \"length\": n} with no digest, and a value whose classification is absent is treated as secret.
     * @type {{ [key: string]: any; }}
     * @memberof CryptographicAssetSourceDto
     */
    payload?: { [key: string]: any };
    /**
     * Occurrence evidence recorded from this source, sorted deterministically and capped; occurrenceCount carries the pre-cap total. May be empty
     * @type {Array<CryptographicAssetEvidenceDto>}
     * @memberof CryptographicAssetSourceDto
     */
    evidence?: Array<CryptographicAssetEvidenceDto>;
}
