// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CryptographicAssetType, PqcVerdict } from './';

/**
 * @export
 * @interface CryptographicAssetDto
 */
export interface CryptographicAssetDto {
    /**
     * UUID of the inventory asset
     * @type {string}
     * @memberof CryptographicAssetDto
     */
    uuid: string;
    /**
     * Normalized display name of the asset
     * @type {string}
     * @memberof CryptographicAssetDto
     */
    name: string;
    /**
     * Type of the asset
     * @type {CryptographicAssetType}
     * @memberof CryptographicAssetDto
     */
    type: CryptographicAssetType;
    /**
     * Post-quantum readiness verdict computed by the platform rule set
     * @type {PqcVerdict}
     * @memberof CryptographicAssetDto
     */
    pqcVerdict: PqcVerdict;
    /**
     * Number of CBOM documents that reference this asset
     * @type {number}
     * @memberof CryptographicAssetDto
     */
    sourceCbomCount: number;
    /**
     * Total number of occurrence evidence entries recorded across all source CBOMs
     * @type {number}
     * @memberof CryptographicAssetDto
     */
    occurrenceCount: number;
    /**
     * True when sources make contradicting claims about this asset that are quarantined pending reconciliation
     * @type {boolean}
     * @memberof CryptographicAssetDto
     */
    quarantined: boolean;
}
