// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PqcExplanationStepDto, PqcVerdict } from './';

/**
 * A PQC verdict recomputed from the asset as stored, rule by rule; nothing is written back. storedVerdict, storedRuleId and storedEvaluatedAt are absent when the asset has not been evaluated yet, and storedRuleId also for a stored verdict no rule decided. When the rule set cannot evaluate the asset, verdict is unknown, ruleId is EVALUATION-FAILED, inputs is empty and steps holds one failed step
 * @export
 * @interface CryptographicAssetPqcExplanationDto
 */
export interface CryptographicAssetPqcExplanationDto {
    /**
     * UUID of the inventory asset the explanation is for
     * @type {string}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    uuid: string;
    /**
     * Post-quantum readiness verdict recomputed from the asset as stored
     * @type {PqcVerdict}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    verdict: PqcVerdict;
    /**
     * The rule that decided the recomputed verdict
     * @type {string}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    ruleId: string;
    /**
     * The deciding rule\'s finding, in the words a stored verdict carries
     * @type {string}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    reason: string;
    /**
     * Values of the asset properties the rules read, as derived from the stored asset. A property the asset does not have is omitted; key material and internal deduplication keys are never served. Values are strings, numbers, booleans or lists of strings, never nested objects. Reference properties are served as the bom-ref strings the producing document recorded, under one key whichever CycloneDX version spelt them
     * @type {{ [key: string]: any; }}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    inputs: { [key: string]: any };
    /**
     * Every rule the evaluation consults for an asset of this type, in evaluation order; rules that apply only to other asset types are not listed. Evaluation is first-match-wins: the rules before the deciding one are notMatched, the deciding one is decided or resolved, and the rules after it are notReached. The deciding step\'s ruleId equals the explanation\'s ruleId
     * @type {Array<PqcExplanationStepDto>}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    steps: Array<PqcExplanationStepDto>;
    /**
     * True when the verdict and rule stored on the asset equal the recomputed ones. False when the asset has not been evaluated yet, or when something its stored verdict was decided from has changed since: the asset itself, the verdict of an asset it refers to, or the platform\'s rules after an upgrade. The stored verdict is served until the asset is next re-evaluated
     * @type {boolean}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    matchesStored: boolean;
    /**
     * The verdict stored on the asset
     * @type {PqcVerdict}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    storedVerdict?: PqcVerdict;
    /**
     * The rule that decided the stored verdict; absent when the asset has not been evaluated yet, or when no rule decided it
     * @type {string}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    storedRuleId?: string;
    /**
     * When the stored verdict was last evaluated; absent when the asset has not been evaluated yet
     * @type {string}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    storedEvaluatedAt?: string;
    /**
     * When this explanation was computed
     * @type {string}
     * @memberof CryptographicAssetPqcExplanationDto
     */
    explainedAt: string;
}
