// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CryptographicAssetSyncCompletenessDto } from './';

/**
 * Cryptographic asset inventory dashboard statistics
 * @export
 * @interface CryptographicAssetStatisticsDto
 */
export interface CryptographicAssetStatisticsDto {
    /**
     * Total number of deduplicated cryptographic assets in the inventory
     * @type {number}
     * @memberof CryptographicAssetStatisticsDto
     */
    totalAssets?: number;
    /**
     * Number of CBOM documents that contributed at least one asset to the inventory; documents whose assets are not yet synced do not count
     * @type {number}
     * @memberof CryptographicAssetStatisticsDto
     */
    sourceCbomCount?: number;
    /**
     * Asset count by asset type. Keys are CryptographicAssetType codes; every type is present, with 0 when none
     * @type {{ [key: string]: number; }}
     * @memberof CryptographicAssetStatisticsDto
     */
    statByType?: { [key: string]: number };
    /**
     * Asset count by PQC readiness verdict. Keys are PqcVerdict codes; every verdict is present, with 0 when none
     * @type {{ [key: string]: number; }}
     * @memberof CryptographicAssetStatisticsDto
     */
    statByPqcVerdict?: { [key: string]: number };
    /**
     * Asset count by algorithm family, limited to the top-N families by count. Use distinctAlgorithmFamilyCount for the total number of families; assets with no family are counted in unassignedAssetCount and never occupy a slot here
     * @type {{ [key: string]: number; }}
     * @memberof CryptographicAssetStatisticsDto
     */
    statByAlgorithmFamily?: { [key: string]: number };
    /**
     * Number of distinct algorithm families across the inventory, excluding assets with no family. Lets the client render a \"+k more\" overflow beyond the top-N entries in statByAlgorithmFamily
     * @type {number}
     * @memberof CryptographicAssetStatisticsDto
     */
    distinctAlgorithmFamilyCount?: number;
    /**
     * Number of assets with no algorithm family, which is common: the family concept does not apply to most related-crypto-material. Never counted in statByAlgorithmFamily or distinctAlgorithmFamilyCount
     * @type {number}
     * @memberof CryptographicAssetStatisticsDto
     */
    unassignedAssetCount?: number;
    /**
     * How completely the inventory reflects the stored CBOM documents
     * @type {CryptographicAssetSyncCompletenessDto}
     * @memberof CryptographicAssetStatisticsDto
     */
    syncCompleteness?: CryptographicAssetSyncCompletenessDto;
}
