// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CryptographicAssetNormalizedFieldsDto
 */
export interface CryptographicAssetNormalizedFieldsDto {
    /**
     * Normalized algorithm family
     * @type {string}
     * @memberof CryptographicAssetNormalizedFieldsDto
     */
    algorithmFamily?: string;
    /**
     * Normalized primitive
     * @type {string}
     * @memberof CryptographicAssetNormalizedFieldsDto
     */
    primitive?: string;
    /**
     * Normalized parameter set
     * @type {string}
     * @memberof CryptographicAssetNormalizedFieldsDto
     */
    parameterSet?: string;
    /**
     * Normalized curve
     * @type {string}
     * @memberof CryptographicAssetNormalizedFieldsDto
     */
    curve?: string;
    /**
     * Normalized mode of operation
     * @type {string}
     * @memberof CryptographicAssetNormalizedFieldsDto
     */
    mode?: string;
    /**
     * Normalized padding
     * @type {string}
     * @memberof CryptographicAssetNormalizedFieldsDto
     */
    padding?: string;
    /**
     * Normalized variant
     * @type {string}
     * @memberof CryptographicAssetNormalizedFieldsDto
     */
    variant?: string;
}
