// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PqcReferencedAssetDto } from './';

/**
 * @export
 * @interface CryptographicAssetVerdictDto
 */
export interface CryptographicAssetVerdictDto {
    /**
     * The rule that decided the verdict; absent when no rule matched and the verdict is the rule set\'s default
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    ruleId?: string;
    /**
     * The deciding rule\'s finding; absent when no rule matched
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    reason?: string;
    /**
     * Values of the asset fields the deciding rule evaluated, recorded at decision time and as stored, so assetType may be unroutable for an asset served with no type. Values are strings, numbers, booleans or lists of strings, never nested objects
     * @type {{ [key: string]: any; }}
     * @memberof CryptographicAssetVerdictDto
     */
    evaluatedFields?: { [key: string]: any };
    /**
     * The inventory asset whose own verdict decided this one. Present only when the deciding rule carried a verdict over from an asset this one refers to; absent when the asset\'s own properties decided, or when the reference could not be resolved
     * @type {PqcReferencedAssetDto}
     * @memberof CryptographicAssetVerdictDto
     */
    referencedAsset?: PqcReferencedAssetDto;
    /**
     * When the current verdict value was decided
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    decidedAt: string;
    /**
     * When the verdict was last evaluated; a re-evaluation that confirms the verdict advances this and not decidedAt
     * @type {string}
     * @memberof CryptographicAssetVerdictDto
     */
    evaluatedAt: string;
}
