// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BaseAttributeContentDtoV3, CryptographicAssetType, PqcVerdict } from './';

/**
 * @export
 * @interface CryptographicAssetDto
 */
export interface CryptographicAssetDto {
    /**
     * UUID of the inventory asset
     * @type {string}
     * @memberof CryptographicAssetDto
     */
    uuid: string;
    /**
     * Normalized display name of the asset: the producers\' name, else the recorded OID. Absent when neither exists to serve, because a refuted OID is never presented as the name
     * @type {string}
     * @memberof CryptographicAssetDto
     */
    name?: string;
    /**
     * Type of the asset
     * @type {CryptographicAssetType}
     * @memberof CryptographicAssetDto
     */
    type: CryptographicAssetType;
    /**
     * Post-quantum readiness verdict computed by the platform rule set
     * @type {PqcVerdict}
     * @memberof CryptographicAssetDto
     */
    pqcVerdict: PqcVerdict;
    /**
     * Number of CBOM documents that reference this asset
     * @type {number}
     * @memberof CryptographicAssetDto
     */
    sourceCbomCount: number;
    /**
     * Total number of occurrence evidence entries recorded across all source CBOMs
     * @type {number}
     * @memberof CryptographicAssetDto
     */
    occurrenceCount: number;
    /**
     * True when sources make contradicting claims about this asset that are quarantined pending reconciliation
     * @type {boolean}
     * @memberof CryptographicAssetDto
     */
    quarantined: boolean;
    /**
     * Values of the attribute-sourced fields requested as columns, keyed by field source and then by field identifier. Present only when the listing request asked for attribute-sourced columns; a field the object has no value for is absent rather than empty, and a multi-valued attribute arrives in its stored item_order.
     * @type {{ [key: string]: { [key: string]: Array<BaseAttributeContentDtoV3>; }; }}
     * @memberof CryptographicAssetDto
     */
    attributeValues?: { [key: string]: { [key: string]: Array<BaseAttributeContentDtoV3> } };
}
