// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface CryptographicAssetOidDto
 */
export interface CryptographicAssetOidDto {
    /**
     * Object identifier as recorded from the producers
     * @type {string}
     * @memberof CryptographicAssetOidDto
     */
    oid: string;
    /**
     * True when the platform determined the identifier does not describe this asset
     * @type {boolean}
     * @memberof CryptographicAssetOidDto
     */
    refuted: boolean;
}
