// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeCallback,
    AttributeContentType,
    AttributeType,
    AttributeVersion,
    BaseAttributeConstraint,
    BaseAttributeContentDtoV3,
    DataAttributeProperties,
    DataAttributeV2,
    DataAttributeV3,
    FieldMapping,
    ValueSource,
} from './';

/**
 * @type DataAttribute
 * Data Attribute
 * @export
 */
export type DataAttribute = DataAttributeV2 | DataAttributeV3;
