// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.14.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    BooleanAttributeContent,
    CodeBlockAttributeContent,
    CredentialAttributeContent,
    DateAttributeContent,
    DateTimeAttributeContent,
    FileAttributeContent,
    FloatAttributeContent,
    IntegerAttributeContent,
    ObjectAttributeContent,
    SecretAttributeContent,
    StringAttributeContent,
    TextAttributeContent,
    TimeAttributeContent,
} from './';

/**
 * @type DataAttributeContent
 * Content of the Attribute
 * @export
 */
export type DataAttributeContent =
    | BooleanAttributeContent
    | CodeBlockAttributeContent
    | CredentialAttributeContent
    | DateAttributeContent
    | DateTimeAttributeContent
    | FileAttributeContent
    | FloatAttributeContent
    | IntegerAttributeContent
    | ObjectAttributeContent
    | SecretAttributeContent
    | StringAttributeContent
    | TextAttributeContent
    | TimeAttributeContent;
