// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveryMessageSeverity } from './';

/**
 * One kind of problem a Discovery run reported, with how often it happened. Repeats aggregate onto the entry already carrying them rather than adding a new one.
 * @export
 * @interface DiscoveryMessageDto
 */
export interface DiscoveryMessageDto {
    /**
     * @type {DiscoveryMessageSeverity}
     * @memberof DiscoveryMessageDto
     */
    severity: DiscoveryMessageSeverity;
    /**
     * Identifier for the kind of problem, from a closed vocabulary — what an operator or a support engineer matches on. Entries are aggregated by code together with the message text, so several entries in one run may share a code.
     * @type {string}
     * @memberof DiscoveryMessageDto
     */
    code: string;
    /**
     * Human-readable description of the problem. Curated text written for a person to read; never a raw exception message, and never text a Discovery Provider authored.
     * @type {string}
     * @memberof DiscoveryMessageDto
     */
    message: string;
    /**
     * How many times this problem occurred during the run. At least 1.
     * @type {number}
     * @memberof DiscoveryMessageDto
     */
    occurrences: number;
    /**
     * When this problem was first seen during the run.
     * @type {string}
     * @memberof DiscoveryMessageDto
     */
    firstSeenAt: string;
    /**
     * When this problem was most recently seen during the run.
     * @type {string}
     * @memberof DiscoveryMessageDto
     */
    lastSeenAt: string;
}
