// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveryResourceProgressDto } from './';

/**
 * Run-level progress of a discovery run: the run-wide counters, plus an optional per-resource breakdown.
 * @export
 * @interface DiscoveryProgressDto
 */
export interface DiscoveryProgressDto {
    /**
     * Number of items processed so far; omitted when the connector cannot report it
     * @type {number}
     * @memberof DiscoveryProgressDto
     */
    processed?: number;
    /**
     * Estimated total number of items for the run; omitted when the connector cannot produce an estimate
     * @type {number}
     * @memberof DiscoveryProgressDto
     */
    totalEstimate?: number;
    /**
     * Connector-defined free-text phase label (e.g. \"scanning\", \"enumerating\"); omitted when the connector has no phase concept
     * @type {string}
     * @memberof DiscoveryProgressDto
     */
    phase?: string;
    /**
     * @type {{ [key: string]: DiscoveryResourceProgressDto; }}
     * @memberof DiscoveryProgressDto
     */
    byResource?: { [key: string]: DiscoveryResourceProgressDto };
}
