// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveryResourceProgressDto } from './';

/**
 * How far a discovery has got: how much of the provider\'s work is done, and optionally how many items it has found per resource type.
 * @export
 * @interface DiscoveryProgressDto
 */
export interface DiscoveryProgressDto {
    /**
     * How many targets the provider has attempted so far, including ones that failed. A target is one unit of the provider\'s work — one address and port, one inventory entry, one keystore alias — and can yield many items or none. Omitted if the provider cannot count its work.
     * @type {number}
     * @memberof DiscoveryProgressDto
     */
    targetsProcessed?: number;
    /**
     * How many targets this discovery will attempt in total — exact if the provider knows, an estimate otherwise, and it may change as the run goes on. Use it with targetsProcessed to show progress. Omitted when the provider cannot know the total; there is then no percentage to show, and clients must not guess one.
     * @type {number}
     * @memberof DiscoveryProgressDto
     */
    targetsTotal?: number;
    /**
     * How many targets could not be examined — an unreachable host, a refused connection, a target that answered nothing usable. Included in targetsProcessed, not added to it, so a mostly dark range still reaches its total. Failures here do not make the discovery itself fail.
     * @type {number}
     * @memberof DiscoveryProgressDto
     */
    targetsFailed?: number;
    /**
     * Free-text label for what the provider is doing (e.g. \"scanning\", \"enumerating\"); omitted if it has none
     * @type {string}
     * @memberof DiscoveryProgressDto
     */
    phase?: string;
    /**
     * How many items were found, broken down by resource type. Present only if the provider reports the breakdown.
     * @type {{ [key: string]: DiscoveryResourceProgressDto; }}
     * @memberof DiscoveryProgressDto
     */
    byResource?: { [key: string]: DiscoveryResourceProgressDto };
    /**
     * When the platform recorded this report. A discovery is polled on a backoff that settles at several minutes, so counters can be older than the response carrying them; this says how much older. Set by the platform — a value sent by a Discovery Provider is ignored.
     * @type {string}
     * @memberof DiscoveryProgressDto
     */
    readonly updatedAt?: string;
}
