// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute, Resource } from './';

/**
 * @export
 * @interface DiscoveryDto
 */
export interface DiscoveryDto {
    /**
     * Discovery name
     * @type {string}
     * @memberof DiscoveryDto
     */
    name: string;
    /**
     * List of Attributes for Discovery
     * @type {Array<RequestAttribute>}
     * @memberof DiscoveryDto
     */
    attributes: Array<RequestAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof DiscoveryDto
     */
    customAttributes?: Array<RequestAttribute>;
    /**
     * Discovery Provider UUID
     * @type {string}
     * @memberof DiscoveryDto
     */
    connectorUuid: string;
    /**
     * Discovery Kind
     * @type {string}
     * @memberof DiscoveryDto
     */
    kind: string;
    /**
     * List of triggers to be triggered after the discovery is finished, triggers will be evaluated in given order
     * @type {Array<string>}
     * @memberof DiscoveryDto
     */
    triggers?: Array<string>;
    /**
     * Resource types this run should discover, as resource wire codes (e.g. \"certificates\", \"keys\"). Omit only for a run against a v1 connector, which keeps exactly today\'s semantics: the run discovers certificates. A v2 connector requires the field — Core rejects a request that omits it — and a v1 connector rejects a request that supplies it: discovery has no resource dimension in v1.
     * @type {Array<Resource>}
     * @memberof DiscoveryDto
     */
    resources?: Array<Resource>;
    /**
     * Per-resource attributes, keyed by resource wire code, collected against the per-resource attribute definitions the connector advertises. Omit for exactly today\'s v1 semantics: only the run-level attributes above are sent to the connector. A key absent from this map means that resource is discovered with no refinement of its own, not that it is excluded — resources alone decides what a run targets.
     * @type {{ [key: string]: Array<RequestAttribute>; }}
     * @memberof DiscoveryDto
     */
    resourceAttributes?: { [key: string]: Array<RequestAttribute> };
}
