// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveredItemPayload, MetadataAttribute, Resource } from './';

/**
 * @export
 * @interface DiscoveryItemDto
 */
export interface DiscoveryItemDto {
    /**
     * UUID of the staged Discovery item
     * @type {string}
     * @memberof DiscoveryItemDto
     */
    uuid: string;
    /**
     * UUID of the object this item became in inventory. Absent until the item is processed, and absent permanently if its processing failed.
     * @type {string}
     * @memberof DiscoveryItemDto
     */
    inventoryUuid?: string;
    /**
     * Position of this item in the run. For runs against a v2 Discovery Provider this is the provider\'s run-wide sequence; for runs against a v1 provider, which never numbered its items, Core synthesizes it from staging order.
     * @type {number}
     * @memberof DiscoveryItemDto
     */
    sequence: number;
    /**
     * Reference identifying this item within the run, unique per resource type. Provider-assigned for v2-staged items; for certificates staged by a v1 provider Core uses the certificate fingerprint, which is the identity it deduplicates on.
     * @type {string}
     * @memberof DiscoveryItemDto
     */
    uniqueRef: string;
    /**
     * When the Discovery Provider reported discovering this item
     * @type {string}
     * @memberof DiscoveryItemDto
     */
    discoveredAt?: string;
    /**
     * Resource-specific data the Discovery Provider reported, discriminated by resource
     * @type {DiscoveredItemPayload}
     * @memberof DiscoveryItemDto
     */
    payload: DiscoveredItemPayload;
    /**
     * True when the object was not already in the inventory at the time this run staged it, false when the run rediscovered something the inventory already held.
     * @type {boolean}
     * @memberof DiscoveryItemDto
     */
    newlyDiscovered: boolean;
    /**
     * Indicator whether processing of the staged item has been attempted; processedError and inventoryUuid convey the outcome.
     * @type {boolean}
     * @memberof DiscoveryItemDto
     */
    processed: boolean;
    /**
     * Reason recorded against this item, if any — not only a failure, and not tied to processed. An item that was handled can carry one, and an item that was never attempted carries one while processed stays false.
     * @type {string}
     * @memberof DiscoveryItemDto
     */
    processedError?: string;
    /**
     * Item metadata as reported by the Discovery Provider — where the item was found (e.g. IP address and port). Absent when the provider reported none.
     * @type {Array<MetadataAttribute>}
     * @memberof DiscoveryItemDto
     */
    meta?: Array<MetadataAttribute>;
    /**
     * @type {Resource}
     * @memberof DiscoveryItemDto
     */
    readonly resource: Resource;
}
