// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * How many items of one resource type have been found, keyed by resource code inside byResource (e.g. \"certificates\", \"keys\"). Every field is optional, but a provider with nothing to report MUST leave the whole object out rather than send an empty one — a client keeping the last progress it was sent cannot tell an empty report from a missing one.
 * @export
 * @interface DiscoveryResourceProgressDto
 */
export interface DiscoveryResourceProgressDto {
    /**
     * How many items of this resource type the provider has found so far; omitted if it cannot count them
     * @type {number}
     * @memberof DiscoveryResourceProgressDto
     */
    produced?: number;
    /**
     * Estimated total number of items of this resource type for the whole discovery; omitted if the provider cannot estimate
     * @type {number}
     * @memberof DiscoveryResourceProgressDto
     */
    totalEstimate?: number;
    /**
     * Free-text label for what the provider is doing with this resource type; omitted if it has none
     * @type {string}
     * @memberof DiscoveryResourceProgressDto
     */
    phase?: string;
}
