// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface DiscoveryCertificateDto
 */
export interface DiscoveryCertificateDto {
    /**
     * UUID of the Certificate
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    uuid: string;
    /**
     * UUID of the Certificate in Certificate inventory
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    inventoryUuid?: string;
    /**
     * Certificate common name
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    commonName: string;
    /**
     * Certificate Serial Number
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    serialNumber: string;
    /**
     * Issuer common name
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    issuerCommonName: string;
    /**
     * Certificate validity start date
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    notBefore: string;
    /**
     * Certificate expiration date
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    notAfter: string;
    /**
     * SHA256 thumbprint of the certificate
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    fingerprint: string;
    /**
     * Base64 encoded Certificate content
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    certificateContent: string;
    /**
     * Boolean representing if the certificate is newly discovered. True - Certificate is newly discoveredfalse - Certificate was already available in the inventory
     * @type {boolean}
     * @memberof DiscoveryCertificateDto
     */
    newlyDiscovered: boolean;
    /**
     * Whether processing of this row has been attempted; processedError conveys the outcome. False means the platform reached no verdict for the row, which may still carry a reason.
     * @type {boolean}
     * @memberof DiscoveryCertificateDto
     */
    processed: boolean;
    /**
     * Reason recorded against this row, if any — not only a failure, and not tied to processed. A row that imported cleanly can carry one (a certificate imported without all of its public keys associated, say), and a row that was never attempted carries one while processed stays false.
     * @type {string}
     * @memberof DiscoveryCertificateDto
     */
    processedError?: string;
}
