// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveredCertificateDto, DiscoveredKeyDto, KeyAlgorithm, KeyFormat, KeyType, Resource } from './';

/**
 * @type DiscoveredItemPayload
 * Resource-specific payload of a discovered item. The required resource property is the discriminator: it carries the resource\'s wire code and selects which concrete payload shape this object is. Each concrete shape fixes it to its own value.
 * @export
 */
export type DiscoveredItemPayload = DiscoveredCertificateDto | DiscoveredKeyDto;
