// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveryProgressDto, DiscoveryStatus, MetadataResponseDto, Resource, ResponseAttribute, TriggerDto } from './';

/**
 * @export
 * @interface DiscoveryDetailDto
 */
export interface DiscoveryDetailDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    name: string;
    /**
     * Discovery Kind
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    kind: string;
    /**
     * @type {DiscoveryStatus}
     * @memberof DiscoveryDetailDto
     */
    status: DiscoveryStatus;
    /**
     * @type {DiscoveryStatus}
     * @memberof DiscoveryDetailDto
     */
    connectorStatus: DiscoveryStatus;
    /**
     * Failure/Success Messages
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    message?: string;
    /**
     * Date and time when Discovery started
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    startTime?: string;
    /**
     * Date and time when Discovery finished
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    endTime?: string;
    /**
     * Number of certificates that are discovered
     * @type {number}
     * @memberof DiscoveryDetailDto
     */
    totalCertificatesDiscovered?: number;
    /**
     * Number of certificates that were discovered by connector
     * @type {number}
     * @memberof DiscoveryDetailDto
     */
    connectorTotalCertificatesDiscovered?: number;
    /**
     * UUID of the Discovery Provider
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    connectorUuid: string;
    /**
     * Name of the Discovery Provider
     * @type {string}
     * @memberof DiscoveryDetailDto
     */
    connectorName: string;
    /**
     * List of Discovery Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof DiscoveryDetailDto
     */
    attributes: Array<ResponseAttribute>;
    /**
     * List of Custom Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof DiscoveryDetailDto
     */
    customAttributes?: Array<ResponseAttribute>;
    /**
     * Metadata of the Discovery
     * @type {Array<MetadataResponseDto>}
     * @memberof DiscoveryDetailDto
     */
    metadata?: Array<MetadataResponseDto>;
    /**
     * List of associated triggers
     * @type {Array<TriggerDto>}
     * @memberof DiscoveryDetailDto
     */
    triggers: Array<TriggerDto>;
    /**
     * Resource types this run targets, as resource wire codes (e.g. \"certificates\", \"keys\"). Always present: a run against a v1 connector reports [\"certificates\"], synthesized by Core, so a client never inspects the connector to learn what a run was after.
     * @type {Array<Resource>}
     * @memberof DiscoveryDetailDto
     */
    resources?: Array<Resource>;
    /**
     * @type {DiscoveryProgressDto}
     * @memberof DiscoveryDetailDto
     */
    progress?: DiscoveryProgressDto;
    /**
     * How many distinct advisory messages this run collected, as counted by the run messages listing. Repeated problems are aggregated, so this counts kinds of problem rather than occurrences. A non-zero count does not imply the run failed. Always 0 for runs against a v1 Discovery Provider.
     * @type {number}
     * @memberof DiscoveryDetailDto
     */
    runMessageCount: number;
    /**
     * Whether this run can be stopped and later resumed. Always present; false for runs against v1 connectors. This flag says whether the run has the capability; the run status decides which control is currently valid (stop while in progress, resume while stopped). The connector may still refuse a stop at runtime past the point of no return.
     * @type {boolean}
     * @memberof DiscoveryDetailDto
     */
    stoppable: boolean;
}
