// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveredItemPayload, KeyAlgorithm, KeyFormat, KeyType, Resource } from './';

/**
 * @type DiscoveredKeyDto
 * A connector reports a key\'s existence, intrinsic metadata, and at most its public part; private, secret and split key material must never be sent. A PRIVATE_KEY, SECRET_KEY or SPLIT_KEY report MUST omit publicKey and publicKeyFormat entirely.
 * @export
 */
export type DiscoveredKeyDto = DiscoveredItemPayload;
