// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Progress counters. Used for a whole run and, keyed by resource code inside byResource (e.g. \"certificates\", \"keys\"), for one resource type at a time. Every field is optional.
 * @export
 * @interface DiscoveryResourceProgressDto
 */
export interface DiscoveryResourceProgressDto {
    /**
     * Number of items processed so far; omitted when the connector cannot report it
     * @type {number}
     * @memberof DiscoveryResourceProgressDto
     */
    processed?: number;
    /**
     * Estimated total number of items for the run; omitted when the connector cannot produce an estimate
     * @type {number}
     * @memberof DiscoveryResourceProgressDto
     */
    totalEstimate?: number;
    /**
     * Connector-defined free-text phase label (e.g. \"scanning\", \"enumerating\"); omitted when the connector has no phase concept
     * @type {string}
     * @memberof DiscoveryResourceProgressDto
     */
    phase?: string;
}
