// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute, SigningWorkflowType } from './';

/**
 * Document signing workflow configuration request
 * @export
 * @interface DocumentSigningWorkflowRequestDto
 */
export interface DocumentSigningWorkflowRequestDto {
    /**
     * Signing workflow type
     * @type {SigningWorkflowType}
     * @memberof DocumentSigningWorkflowRequestDto
     */
    type: SigningWorkflowType;
    /**
     * UUID of the Signature Formatting Provider that constructs the data-to-be-signed (DTBS) for Document signing. Required for ILM-managed signing; must be omitted for delegated signing.
     * @type {string}
     * @memberof DocumentSigningWorkflowRequestDto
     */
    signatureFormattingConnectorUuid?: string;
    /**
     * Attributes for the Signature Formatting Provider that control DTBS construction for the document signing workflow. Applicable only when ILM-managed signing is used.
     * @type {Array<RequestAttribute>}
     * @memberof DocumentSigningWorkflowRequestDto
     */
    signatureFormattingConnectorAttributes?: Array<RequestAttribute>;
}
