// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FieldSource, FieldType, MappedField } from './';

/**
 * @type ExtendedKeyUsageMappedField
 * Maps an attribute to the Extended Key Usage extension; the permitted purposes are the attribute\'s content, resolved against the EXTENDED_KEY_USAGE OID registry
 * @export
 */
export type ExtendedKeyUsageMappedField = MappedField;
