// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.16.1
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Float attribute content for decimal numbers
 * @export
 * @interface FloatAttributeContent
 */
export interface FloatAttributeContent {
    /**
     * Content Reference
     * @type {string}
     * @memberof FloatAttributeContent
     */
    reference?: string;
    /**
     * Float attribute value
     * @type {number}
     * @memberof FloatAttributeContent
     */
    data: number;
}
