// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { HealthStatus } from './';

/**
 * @export
 * @interface HealthInfoComponent
 */
export interface HealthInfoComponent {
    /**
     * Current status of component
     * @type {HealthStatus}
     * @memberof HealthInfoComponent
     */
    status: HealthStatus;
    /**
     * Additional details about the component status
     * @type {{ [key: string]: any; }}
     * @memberof HealthInfoComponent
     */
    details?: { [key: string]: any };
}
