// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * What became of one entry\'s certificate or key: made by this call, already in the inventory, or a private key added to an existing public-key record.
 * @export
 * @enum {string}
 */
export enum ImportOutcome {
    Created = 'created',
    Existing = 'existing',
    Adopted = 'adopted',
}
