// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InspectedEntryDto } from './';

/**
 * Entries found in an uploaded file
 * @export
 * @interface InspectionResponseDto
 */
export interface InspectionResponseDto {
    /**
     * The lowercase hex SHA-256 of the uploaded file, so a caller can tell two uploads apart and confirm the file it is about to import is the one it read
     * @type {string}
     * @memberof InspectionResponseDto
     */
    containerDigest: string;
    /**
     * Entries found in the file
     * @type {Array<InspectedEntryDto>}
     * @memberof InspectionResponseDto
     */
    entries: Array<InspectedEntryDto>;
}
