// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The file to read and the options for reading it
 * @export
 * @interface InspectionRequestDto
 */
export interface InspectionRequestDto {
    /**
     * Content of the uploaded file, base64-encoded: a container such as PKCS#12 or PEM, a standalone key, or a certificate. At most 5 MiB decoded. The platform holds it in memory only, never writes it anywhere and never echoes it in an error, since the file may carry key material.
     * @type {string}
     * @memberof InspectionRequestDto
     */
    file: string;
    /**
     * Passphrase that opens the uploaded file. Absent for a file that carries no protection of its own.
     * @type {string}
     * @memberof InspectionRequestDto
     */
    passphrase?: string;
    /**
     * Token profile the caller intends to import key material into. When given, each entry is reported with whether that profile can hold it.
     * @type {string}
     * @memberof InspectionRequestDto
     */
    tokenProfileUuid?: string;
}
