// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InspectedEntryKind, KeyAlgorithm } from './';

/**
 * One entry found in an uploaded file
 * @export
 * @interface InspectedEntryDto
 */
export interface InspectedEntryDto {
    /**
     * Reference for this entry, used to select it when importing.  The lowercase hex SHA-256 of the entry\'s DER: of the certificate for a certificate, of the `SubjectPublicKeyInfo` for a key pair or private key, of the key as the file holds it for a secret key or a key of an algorithm the platform does not support, and of the request for a certificate request. It is never derived from the entry\'s position in the file, so a reference cannot come to mean a different entry between inspecting and importing.
     * @type {string}
     * @memberof InspectedEntryDto
     */
    entryReference: string;
    /**
     * What this entry turned out to be
     * @type {InspectedEntryKind}
     * @memberof InspectedEntryDto
     */
    kind: InspectedEntryKind;
    /**
     * The name the file gives the entry, such as a keystore alias or a PKCS#12 friendly name
     * @type {string}
     * @memberof InspectedEntryDto
     */
    alias?: string;
    /**
     * Subject distinguished name of the entry\'s certificate
     * @type {string}
     * @memberof InspectedEntryDto
     */
    subjectDn?: string;
    /**
     * Issuer distinguished name of the entry\'s certificate
     * @type {string}
     * @memberof InspectedEntryDto
     */
    issuerDn?: string;
    /**
     * Serial number of the entry\'s certificate
     * @type {string}
     * @memberof InspectedEntryDto
     */
    serialNumber?: string;
    /**
     * SHA-256 fingerprint of the entry\'s certificate
     * @type {string}
     * @memberof InspectedEntryDto
     */
    fingerprint?: string;
    /**
     * Start of the certificate\'s validity
     * @type {string}
     * @memberof InspectedEntryDto
     */
    notBefore?: string;
    /**
     * End of the certificate\'s validity
     * @type {string}
     * @memberof InspectedEntryDto
     */
    notAfter?: string;
    /**
     * Subject alternative names of the entry\'s certificate
     * @type {Array<string>}
     * @memberof InspectedEntryDto
     */
    subjectAlternativeNames?: Array<string>;
    /**
     * Algorithm of the entry\'s key, where it can be determined without opening protected material
     * @type {KeyAlgorithm}
     * @memberof InspectedEntryDto
     */
    keyAlgorithm?: KeyAlgorithm;
    /**
     * Length of the entry\'s key in bits, where it can be determined
     * @type {number}
     * @memberof InspectedEntryDto
     */
    keyLength?: number;
    /**
     * Number of certificates found with this entry, including the entry\'s own certificate
     * @type {number}
     * @memberof InspectedEntryDto
     */
    chainLength?: number;
    /**
     * Whether the entry\'s key material can be imported into the token profile the inspection named. Absent when the inspection named no token profile.
     * @type {boolean}
     * @memberof InspectedEntryDto
     */
    importable?: boolean;
    /**
     * Why the entry cannot be imported, when it cannot
     * @type {string}
     * @memberof InspectedEntryDto
     */
    notImportableReason?: string;
}
