// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimestampSourceRequestDto, TimestampSourceType } from './';

/**
 * @type InternalTimestampSourceRequestDto
 * Timestamp source referencing a Timestamping Signing Profile on this platform by UUID, as supplied on create and update
 * @export
 */
export type InternalTimestampSourceRequestDto = TimestampSourceRequestDto;
