// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NameAndUuidDto, TimestampSourceDto, TimestampSourceType } from './';

/**
 * @type InternalTimestampSourceDto
 * Timestamp source referencing the Timestamping Signing Profile on this platform that issues the timestamps
 * @export
 */
export type InternalTimestampSourceDto = TimestampSourceDto;
