// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AttributeConstraintType } from './';

/**
 * JSON Schema attribute constraint restricting a string value to JSON conforming to an inline JSON Schema (draft 2020-12)
 * @export
 * @interface JsonSchemaAttributeConstraint
 */
export interface JsonSchemaAttributeConstraint {
    /**
     * Description of the constraint
     * @type {string}
     * @memberof JsonSchemaAttributeConstraint
     */
    description?: string;
    /**
     * Error message to be displayed for wrong data
     * @type {string}
     * @memberof JsonSchemaAttributeConstraint
     */
    errorMessage?: string;
    /**
     * Attribute Constraint Type
     * @type {AttributeConstraintType}
     * @memberof JsonSchemaAttributeConstraint
     */
    type: AttributeConstraintType;
    /**
     * Inline JSON Schema document the value must conform to
     * @type {string}
     * @memberof JsonSchemaAttributeConstraint
     */
    data: string;
}
