// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Reason the configured JWK Set could not be loaded for display
 * @export
 * @enum {string}
 */
export enum JwkSetLoadFailure {
    Unavailable = 'unavailable',
    Invalid = 'invalid',
    TooLarge = 'tooLarge',
}
