// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FieldSource, FieldType, MappedField } from './';

/**
 * @type KeyUsageMappedField
 * Maps an attribute to the Key Usage extension; the permitted bits are the attribute\'s content, taken from CertificateKeyUsage
 * @export
 */
export type KeyUsageMappedField = MappedField;
