// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListViewColumnDto, ListViewFilterDto, Resource, SearchSortRequestDto } from './';

/**
 * @export
 * @interface ListViewDto
 */
export interface ListViewDto {
    /**
     * UUID of the view
     * @type {string}
     * @memberof ListViewDto
     */
    uuid: string;
    /**
     * Name of the view
     * @type {string}
     * @memberof ListViewDto
     */
    name: string;
    /**
     * Resource whose listing the view applies to
     * @type {Resource}
     * @memberof ListViewDto
     */
    resource: Resource;
    /**
     * Columns of the view, in display order. A column whose field the resource no longer defines, such as a deleted attribute, or whose attribute identifier is now backed by a different definition, is still returned with its `status` saying so, so a client can show it as dormant and offer to remove or rebind it.
     * @type {Array<ListViewColumnDto>}
     * @memberof ListViewDto
     */
    columns: Array<ListViewColumnDto>;
    /**
     * Whether this view applies when the listing is opened
     * @type {boolean}
     * @memberof ListViewDto
     */
    defaultView: boolean;
    /**
     * Filters the view applies. Absent or empty means the view shows the whole inventory. Only a filter whose `status` is `available` is meant to be applied to the listing.
     * @type {Array<ListViewFilterDto>}
     * @memberof ListViewDto
     */
    filters?: Array<ListViewFilterDto>;
    /**
     * Ordering the view applies. Absent means the endpoint\'s own default ordering, which is also what a stored ordering reads back as once the listing cannot order by its field, or once that field is an attribute no longer backed by the definitions the ordering was bound to when it was saved.
     * @type {SearchSortRequestDto}
     * @memberof ListViewDto
     */
    sort?: SearchSortRequestDto;
}
