// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListViewColumnDto, ListViewFilterDto, ListViewSortRequestDto } from './';

/**
 * @export
 * @interface ListViewUpdateRequestDto
 */
export interface ListViewUpdateRequestDto {
    /**
     * Name of the view, unique per user and resource
     * @type {string}
     * @memberof ListViewUpdateRequestDto
     */
    name: string;
    /**
     * Columns of the view, in display order. A column whose field the resource no longer defines, such as a deleted attribute, or can no longer show as a column is accepted only when editing a view that already holds it; a new view may name only fields the resource defines and can show. A column the view already holds is never bound to a replacement definition unless it is sent with `rebind`; see the column\'s `rebind` for how its binding is carried over.
     * @type {Array<ListViewColumnDto>}
     * @memberof ListViewUpdateRequestDto
     */
    columns: Array<ListViewColumnDto>;
    /**
     * Whether this view applies when the listing is opened. At most one view per user and resource is the default; marking a view default clears the flag on the previous one.
     * @type {boolean}
     * @memberof ListViewUpdateRequestDto
     */
    defaultView?: boolean;
    /**
     * Filters the view applies. Absent or empty means the view applies no filter of its own and shows the whole inventory. A filter on a field the resource no longer defines is accepted only when editing a view that already holds that exact filter. A filter the view already holds is never bound to a replacement definition unless it is sent with `rebind`; see the filter\'s `rebind` for how its binding is carried over.
     * @type {Array<ListViewFilterDto>}
     * @memberof ListViewUpdateRequestDto
     */
    filters?: Array<ListViewFilterDto>;
    /**
     * Ordering the view applies. Absent means the view falls back to the endpoint\'s own default ordering. An ordering the view already holds is never bound to a replacement definition unless it is sent with `rebind`; see the ordering\'s `rebind` for how its binding is carried over. Unlike a column or a filter, an ordering is refused once the listing no longer offers its field or can no longer order by it, even one the view already holds, so a client drops an ordering the view no longer returns rather than sending it back.
     * @type {ListViewSortRequestDto}
     * @memberof ListViewUpdateRequestDto
     */
    sort?: ListViewSortRequestDto;
}
