// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListViewColumnDto, Resource, SearchFilterRequestDto, SearchSortRequestDto } from './';

/**
 * @export
 * @interface ListViewDto
 */
export interface ListViewDto {
    /**
     * UUID of the view
     * @type {string}
     * @memberof ListViewDto
     */
    uuid: string;
    /**
     * Name of the view
     * @type {string}
     * @memberof ListViewDto
     */
    name: string;
    /**
     * Resource whose listing the view applies to
     * @type {Resource}
     * @memberof ListViewDto
     */
    resource: Resource;
    /**
     * Columns of the view, in display order. A column whose field the resource no longer defines, such as a deleted attribute, is still returned, so a client can show it as unavailable and offer to remove it.
     * @type {Array<ListViewColumnDto>}
     * @memberof ListViewDto
     */
    columns: Array<ListViewColumnDto>;
    /**
     * Whether this view applies when the listing is opened
     * @type {boolean}
     * @memberof ListViewDto
     */
    defaultView: boolean;
    /**
     * Filters the view applies. Absent or empty means the view shows the whole inventory.
     * @type {Array<SearchFilterRequestDto>}
     * @memberof ListViewDto
     */
    filters?: Array<SearchFilterRequestDto>;
    /**
     * Ordering the view applies. Absent means the endpoint\'s own default ordering.
     * @type {SearchSortRequestDto}
     * @memberof ListViewDto
     */
    sort?: SearchSortRequestDto;
}
