// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FilterConditionOperator, FilterFieldSource, ListViewFieldStatus } from './';

/**
 * @export
 * @interface ListViewFilterDto
 */
export interface ListViewFilterDto {
    /**
     * Field group of search filter
     * @type {FilterFieldSource}
     * @memberof ListViewFilterDto
     */
    fieldSource: FilterFieldSource;
    /**
     * Field identifier of search filter. List of available fields with their identifiers can be retrieved from the resource\'s searchable-fields operation, e.g.: [**GET /v1/certificates/search**](../core-certificate/#tag/Certificate-Inventory/operation/getSearchableFieldInformation)
     * @type {string}
     * @memberof ListViewFilterDto
     */
    fieldIdentifier: string;
    /**
     * Condition for the search filter
     * @type {FilterConditionOperator}
     * @memberof ListViewFilterDto
     */
    condition: FilterConditionOperator;
    /**
     * @type {any}
     * @memberof ListViewFilterDto
     */
    value?: any | null;
    /**
     * Attribute definitions the filter is bound to, set by the server when the filter is added or rebound. Absent for a property filter. Only definitions of the view\'s resource count. Empty for an attribute filter whose definition was already gone when stored views were first bound. A value sent in a request is ignored.
     * @type {Array<string>}
     * @memberof ListViewFilterDto
     */
    attributeDefinitionUuids?: Array<string>;
    /**
     * How the filter resolves for the caller when the view is read. A client applies only an `available` filter to the listing; an `unavailable` or `replaced` one is dormant and offered for removal, and a `replaced` one also for rebinding. Returned on every read and write response; a value sent in a request is ignored.
     * @type {ListViewFieldStatus}
     * @memberof ListViewFilterDto
     */
    readonly status?: ListViewFieldStatus;
    /**
     * Set to true to bind an attribute filter the view already holds to the attribute definitions now behind its identifier, which is how a client accepts a `replaced` filter. Absent or false carries a filter the view already holds over: while it still resolves it follows the definitions currently behind its identifier, and once it no longer does it keeps the binding it had, so a replacement never takes it over. Any other filter is bound to the current definitions. Any filter sent with rebind is held to the catalogue as a newly added one, property filters included, but only an attribute filter has a binding to change. The flag is not stored.
     * @type {boolean}
     * @memberof ListViewFilterDto
     */
    rebind?: boolean;
}
