// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListViewColumnDto, Resource, SearchFilterRequestDto, SearchSortRequestDto } from './';

/**
 * @export
 * @interface ListViewRequestDto
 */
export interface ListViewRequestDto {
    /**
     * Name of the view, unique per user and resource
     * @type {string}
     * @memberof ListViewRequestDto
     */
    name: string;
    /**
     * Columns of the view, in display order. A column whose field the resource no longer defines, such as a deleted attribute, or can no longer show as a column is accepted only when editing a view that already holds it; a new view may name only fields the resource defines and can show.
     * @type {Array<ListViewColumnDto>}
     * @memberof ListViewRequestDto
     */
    columns: Array<ListViewColumnDto>;
    /**
     * Whether this view applies when the listing is opened. At most one view per user and resource is the default; marking a view default clears the flag on the previous one.
     * @type {boolean}
     * @memberof ListViewRequestDto
     */
    defaultView?: boolean;
    /**
     * Filters the view applies. Absent or empty means the view applies no filter of its own and shows the whole inventory. A filter on a field the resource no longer defines is accepted only when editing a view that already filters on that field.
     * @type {Array<SearchFilterRequestDto>}
     * @memberof ListViewRequestDto
     */
    filters?: Array<SearchFilterRequestDto>;
    /**
     * Ordering the view applies. Absent means the view falls back to the endpoint\'s own default ordering.
     * @type {SearchSortRequestDto}
     * @memberof ListViewRequestDto
     */
    sort?: SearchSortRequestDto;
    /**
     * Resource whose listing the view applies to
     * @type {Resource}
     * @memberof ListViewRequestDto
     */
    resource: Resource;
}
