// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FilterFieldSource, SortDirection } from './';

/**
 * @export
 * @interface ListViewSortRequestDto
 */
export interface ListViewSortRequestDto {
    /**
     * Field source of the field to sort by
     * @type {FilterFieldSource}
     * @memberof ListViewSortRequestDto
     */
    fieldSource: FilterFieldSource;
    /**
     * Field identifier of the field to sort by. Available fields with their identifiers can be retrieved from the resource\'s searchable-fields operation, for example `GET /v1/certificates/search` or `GET /v2/connectors/search`; only fields marked as sortable may be sorted by.
     * @type {string}
     * @memberof ListViewSortRequestDto
     */
    fieldIdentifier: string;
    /**
     * Direction of the ordering
     * @type {SortDirection}
     * @memberof ListViewSortRequestDto
     */
    direction: SortDirection;
    /**
     * Set to true when the user chose this ordering now, to bind an attribute ordering to the attribute definitions currently behind its identifier. Absent or false carries an ordering sent exactly as the view stores it - same field and direction - over, provided the listing still offers its field and can order by it: while it still resolves it follows the definitions currently behind its identifier, and once it no longer does, because the attribute was replaced, it keeps the binding it had, so the replacement never takes it over and the view reads back without it. Any other ordering is bound to the current definitions. Only an attribute ordering has a binding to change. The flag is not stored.
     * @type {boolean}
     * @memberof ListViewSortRequestDto
     */
    rebind?: boolean;
}
