// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListViewColumnDto, SearchFilterRequestDto, SearchSortRequestDto } from './';

/**
 * @export
 * @interface ListViewUpdateRequestDto
 */
export interface ListViewUpdateRequestDto {
    /**
     * Name of the view, unique per user and resource
     * @type {string}
     * @memberof ListViewUpdateRequestDto
     */
    name: string;
    /**
     * Columns of the view, in display order
     * @type {Array<ListViewColumnDto>}
     * @memberof ListViewUpdateRequestDto
     */
    columns: Array<ListViewColumnDto>;
    /**
     * Whether this view applies when the listing is opened. At most one view per user and resource is the default; marking a view default clears the flag on the previous one.
     * @type {boolean}
     * @memberof ListViewUpdateRequestDto
     */
    defaultView?: boolean;
    /**
     * Filters the view applies. Absent or empty means the view applies no filter of its own and shows the whole inventory.
     * @type {Array<SearchFilterRequestDto>}
     * @memberof ListViewUpdateRequestDto
     */
    filters?: Array<SearchFilterRequestDto>;
    /**
     * Ordering the view applies. Absent means the view falls back to the endpoint\'s own default ordering.
     * @type {SearchSortRequestDto}
     * @memberof ListViewUpdateRequestDto
     */
    sort?: SearchSortRequestDto;
}
