// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * @export
 * @interface ManuallyIssueCertificateRequestDto
 */
export interface ManuallyIssueCertificateRequestDto {
    /**
     * Base64 Content of the Certificate
     * @type {string}
     * @memberof ManuallyIssueCertificateRequestDto
     */
    certificate: string;
    /**
     * Custom Attributes for the Certificate
     * @type {Array<RequestAttribute>}
     * @memberof ManuallyIssueCertificateRequestDto
     */
    customAttributes: Array<RequestAttribute>;
    /**
     * Identify-operation dynamic attributes, as listed by GET /v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/identify for the certificate\'s RA profile. Optional — an authority that offers no identify schema needs none.
     * @type {Array<RequestAttribute>}
     * @memberof ManuallyIssueCertificateRequestDto
     */
    identifyAttributes?: Array<RequestAttribute>;
}
