// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeType,
    AttributeVersion,
    BaseAttributeContentDtoV3,
    MetadataAttributeProperties,
    MetadataAttributeV2,
    MetadataAttributeV3,
} from './';

/**
 * @type MetadataAttribute
 * Metadata Attribute definition
 * @export
 */
export type MetadataAttribute = MetadataAttributeV2 | MetadataAttributeV3;
