// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute, SearchFilterRequestDto } from './';

/**
 * @export
 * @interface MultipleCertificateObjectUpdateDto
 */
export interface MultipleCertificateObjectUpdateDto {
    /**
     * Certificate Groups UUIDs (set to empty list to remove certificate from all groups)
     * @type {Array<string>}
     * @memberof MultipleCertificateObjectUpdateDto
     */
    groupUuids?: Array<string>;
    /**
     * Certificate owner user UUID (set to empty string to remove owner of certificate)
     * @type {string}
     * @memberof MultipleCertificateObjectUpdateDto
     */
    ownerUuid?: string;
    /**
     * RA Profile UUID (set to empty string to remove certificate from RA profile)
     * @type {string}
     * @memberof MultipleCertificateObjectUpdateDto
     */
    raProfileUuid?: string;
    /**
     * Identify-operation dynamic attributes, as listed by GET /v1/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/identify for the target RA profile. Used only when raProfileUuid assigns a new RA profile, which identifies each certificate at its authority. Applies to every certificate in the batch: the request carries a single raProfileUuid, so one authority and one identify schema govern the whole update. Optional — an authority that offers no identify schema needs none.
     * @type {Array<RequestAttribute>}
     * @memberof MultipleCertificateObjectUpdateDto
     */
    attributes?: Array<RequestAttribute>;
    /**
     * List of Certificate UUIDs
     * @type {Array<string>}
     * @memberof MultipleCertificateObjectUpdateDto
     */
    certificateUuids?: Array<string>;
    /**
     * Certificate filter input
     * @type {Array<SearchFilterRequestDto>}
     * @memberof MultipleCertificateObjectUpdateDto
     */
    filters?: Array<SearchFilterRequestDto>;
}
