// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NotificationDataCategory, RecipientType } from './';

/**
 * @export
 * @interface NotificationProfileUpdateRequestDto
 */
export interface NotificationProfileUpdateRequestDto {
    /**
     * Description of the Notification profile
     * @type {string}
     * @memberof NotificationProfileUpdateRequestDto
     */
    description?: string;
    /**
     * Recipient type of notifications produced by profile
     * @type {RecipientType}
     * @memberof NotificationProfileUpdateRequestDto
     */
    recipientType: RecipientType;
    /**
     * Recipient UUIDs of notifications produced by profile
     * @type {Array<string>}
     * @memberof NotificationProfileUpdateRequestDto
     */
    recipientUuids?: Array<string>;
    /**
     * Notification instance UUID
     * @type {string}
     * @memberof NotificationProfileUpdateRequestDto
     */
    notificationInstanceUuid?: string;
    /**
     * Is notification profile sending internal notifications
     * @type {boolean}
     * @memberof NotificationProfileUpdateRequestDto
     */
    internalNotification: boolean;
    /**
     * Frequency of repeated notification
     * @type {string}
     * @memberof NotificationProfileUpdateRequestDto
     */
    frequency?: string;
    /**
     * Maximum number of repetitions of same notification
     * @type {number}
     * @memberof NotificationProfileUpdateRequestDto
     */
    repetitions?: number;
    /**
     * Notification data categories included in external notifications sent by this profile. Presence-aware on update: absent keeps the current value, an empty list disables enrichment
     * @type {Array<NotificationDataCategory>}
     * @memberof NotificationProfileUpdateRequestDto
     */
    eventDataCategories?: Array<NotificationDataCategory>;
}
