// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface ObjectPermissionsRequestDto
 */
export interface ObjectPermissionsRequestDto {
    /**
     * UUID of the Object
     * @type {string}
     * @memberof ObjectPermissionsRequestDto
     */
    uuid: string;
    /**
     * Name of the Object
     * @type {string}
     * @memberof ObjectPermissionsRequestDto
     */
    name: string;
    /**
     * Allowed Action list
     * @type {Array<string>}
     * @memberof ObjectPermissionsRequestDto
     */
    allow?: Array<string>;
    /**
     * Denied Action list
     * @type {Array<string>}
     * @memberof ObjectPermissionsRequestDto
     */
    deny?: Array<string>;
}
