// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateOperationKind } from './';

/**
 * Per-operation support flags for an authority/RA profile.
 * @export
 * @interface OperationSupport
 */
export interface OperationSupport {
    /**
     * Operation kind (ISSUE, RENEW, REVOKE, REGISTER).
     * @type {CertificateOperationKind}
     * @memberof OperationSupport
     */
    operation: CertificateOperationKind;
    /**
     * Whether the operation is supported by this authority.
     * @type {boolean}
     * @memberof OperationSupport
     */
    supported?: boolean;
    /**
     * Whether the platform provides managed status-polling for this operation\'s asynchronous completion (the authority is v3 and advertises status polling). A connector may still complete asynchronously without this — the certificate is then left in a pending state for an operator finalize/confirm action.
     * @type {boolean}
     * @memberof OperationSupport
     */
    asyncSupported?: boolean;
    /**
     * Whether an in-flight asynchronous execution of this operation can be cancelled.
     * @type {boolean}
     * @memberof OperationSupport
     */
    cancelSupported?: boolean;
}
