// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TspProfileListDto } from './';

/**
 * Paginated list of TSP Profiles
 * @export
 * @interface PaginationResponseDtoTspProfileListDto
 */
export interface PaginationResponseDtoTspProfileListDto {
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginationResponseDtoTspProfileListDto
     */
    totalItems?: number;
    /**
     * Page items
     * @type {Array<TspProfileListDto>}
     * @memberof PaginationResponseDtoTspProfileListDto
     */
    items?: Array<TspProfileListDto>;
}
