// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CbomContributedAssetDto } from './';

/**
 * @export
 * @interface PaginationResponseDtoCbomContributedAssetDto
 */
export interface PaginationResponseDtoCbomContributedAssetDto {
    /**
     * Items returned
     * @type {Array<CbomContributedAssetDto>}
     * @memberof PaginationResponseDtoCbomContributedAssetDto
     */
    items: Array<CbomContributedAssetDto>;
    /**
     * Number of entries per page
     * @type {number}
     * @memberof PaginationResponseDtoCbomContributedAssetDto
     */
    itemsPerPage: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof PaginationResponseDtoCbomContributedAssetDto
     */
    pageNumber: number;
    /**
     * Number of pages available
     * @type {number}
     * @memberof PaginationResponseDtoCbomContributedAssetDto
     */
    totalPages: number;
    /**
     * Number of items available
     * @type {number}
     * @memberof PaginationResponseDtoCbomContributedAssetDto
     */
    totalItems: number;
}
