// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DiscoveryMessageDto } from './';

/**
 * @export
 * @interface PaginationResponseDtoDiscoveryMessageDto
 */
export interface PaginationResponseDtoDiscoveryMessageDto {
    /**
     * Items returned
     * @type {Array<DiscoveryMessageDto>}
     * @memberof PaginationResponseDtoDiscoveryMessageDto
     */
    items: Array<DiscoveryMessageDto>;
    /**
     * Number of entries per page
     * @type {number}
     * @memberof PaginationResponseDtoDiscoveryMessageDto
     */
    itemsPerPage: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof PaginationResponseDtoDiscoveryMessageDto
     */
    pageNumber: number;
    /**
     * Number of pages available
     * @type {number}
     * @memberof PaginationResponseDtoDiscoveryMessageDto
     */
    totalPages: number;
    /**
     * Number of items available
     * @type {number}
     * @memberof PaginationResponseDtoDiscoveryMessageDto
     */
    totalItems: number;
}
