// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CertificateSettingsUpdateDto, UtilsSettingsDto } from './';

/**
 * @export
 * @interface PlatformSettingsUpdateDto
 */
export interface PlatformSettingsUpdateDto {
    /**
     * Utils settings of the platform. When present, stored as sent: a URL left out is cleared, and a CBOM sync tunable left out returns to the platform default
     * @type {UtilsSettingsDto}
     * @memberof PlatformSettingsUpdateDto
     */
    utils?: UtilsSettingsDto;
    /**
     * Settings applicable to all certificates in inventory by default
     * @type {CertificateSettingsUpdateDto}
     * @memberof PlatformSettingsUpdateDto
     */
    certificates?: CertificateSettingsUpdateDto;
}
