// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum PlatformEnum {
    Resource = 'Resource',
    ResourceAction = 'ResourceAction',
    FilterConditionOperator = 'FilterConditionOperator',
    FilterFieldType = 'FilterFieldType',
    FilterFieldSource = 'FilterFieldSource',
    SortDirection = 'SortDirection',
    SettingsSection = 'SettingsSection',
    AuthType = 'AuthType',
    HealthStatus = 'HealthStatus',
    ConnectorStatus = 'ConnectorStatus',
    FunctionGroupCode = 'FunctionGroupCode',
    ConnectorVersion = 'ConnectorVersion',
    ConnectorInterface = 'ConnectorInterface',
    FeatureFlag = 'FeatureFlag',
    CertificateType = 'CertificateType',
    CertificateState = 'CertificateState',
    CertificateValidationStatus = 'CertificateValidationStatus',
    CertificateFormat = 'CertificateFormat',
    CertificateFormatEncoding = 'CertificateFormatEncoding',
    CertificateValidationCheck = 'CertificateValidationCheck',
    CertificateRevocationReason = 'CertificateRevocationReason',
    CertificateRequestFormat = 'CertificateRequestFormat',
    DiscoveryStatus = 'DiscoveryStatus',
    DiscoveryMessageSeverity = 'DiscoveryMessageSeverity',
    CertificateProtocol = 'CertificateProtocol',
    CertificateSubjectType = 'CertificateSubjectType',
    CertificateKeyUsage = 'CertificateKeyUsage',
    CertificateRelationType = 'CertificateRelationType',
    OidCategory = 'OidCategory',
    KeyAlgorithm = 'KeyAlgorithm',
    KeyFormat = 'KeyFormat',
    KeyState = 'KeyState',
    KeyType = 'KeyType',
    KeyUsage = 'KeyUsage',
    KeyRequestType = 'KeyRequestType',
    KeyCompromiseReason = 'KeyCompromiseReason',
    TokenInstanceStatus = 'TokenInstanceStatus',
    DigestAlgorithm = 'DigestAlgorithm',
    RsaSignatureScheme = 'RsaSignatureScheme',
    RsaEncryptionScheme = 'RsaEncryptionScheme',
    ComplianceStatus = 'ComplianceStatus',
    ComplianceRuleStatus = 'ComplianceRuleStatus',
    AccountStatus = 'AccountStatus',
    ProtectionMethod = 'ProtectionMethod',
    CmpProfileVariant = 'CmpProfileVariant',
    ProtocolChallengeSource = 'ProtocolChallengeSource',
    AttributeType = 'AttributeType',
    AttributeContentType = 'AttributeContentType',
    AttributeConstraintType = 'AttributeConstraintType',
    AttributeValueTarget = 'AttributeValueTarget',
    ProgrammingLanguageEnum = 'ProgrammingLanguageEnum',
    AttributeVersion = 'AttributeVersion',
    ProtectionLevel = 'ProtectionLevel',
    SchedulerJobExecutionStatus = 'SchedulerJobExecutionStatus',
    RecipientType = 'RecipientType',
    NotificationDataCategory = 'NotificationDataCategory',
    TriggerType = 'TriggerType',
    ConditionType = 'ConditionType',
    ExecutionType = 'ExecutionType',
    ResourceEvent = 'ResourceEvent',
    Module = 'Module',
    ActorType = 'ActorType',
    AuthMethod = 'AuthMethod',
    Operation = 'Operation',
    OperationResult = 'OperationResult',
    ApprovalStatusEnum = 'ApprovalStatusEnum',
    SecretType = 'SecretType',
    KeyStoreType = 'KeyStoreType',
    SecretState = 'SecretState',
    ManagedSigningType = 'ManagedSigningType',
    QcType = 'QcType',
    SignatureFamily = 'SignatureFamily',
    SignatureLevel = 'SignatureLevel',
    SigningProtocol = 'SigningProtocol',
    SigningScheme = 'SigningScheme',
    SigningWorkflowType = 'SigningWorkflowType',
    TimestampSourceType = 'TimestampSourceType',
    TspAuthenticationMethod = 'TspAuthenticationMethod',
    CbomAssetSyncState = 'CbomAssetSyncState',
    CryptographicAssetType = 'CryptographicAssetType',
    PqcVerdict = 'PqcVerdict',
}
