// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BrandingSettingsDto, CertificateSettingsDto, UtilsSettingsDto } from './';

/**
 * @export
 * @interface PlatformSettingsDto
 */
export interface PlatformSettingsDto {
    /**
     * Utils settings of the platform
     * @type {UtilsSettingsDto}
     * @memberof PlatformSettingsDto
     */
    utils?: UtilsSettingsDto;
    /**
     * Settings applicable to all certificates in inventory by default
     * @type {CertificateSettingsDto}
     * @memberof PlatformSettingsDto
     */
    certificates?: CertificateSettingsDto;
    /**
     * Branding applied across the platform user interface
     * @type {BrandingSettingsDto}
     * @memberof PlatformSettingsDto
     */
    branding?: BrandingSettingsDto;
}
