// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PqcExplanationStepOutcome, PqcReferencedAssetDto, PqcVerdict } from './';

/**
 * One rule of the PQC rule set as the explanation walked it. verdict is present on decided, resolved and failed steps; evaluatedFields is absent on a notReached step; referencedAsset is present on a resolved step only
 * @export
 * @interface PqcExplanationStepDto
 */
export interface PqcExplanationStepDto {
    /**
     * The rule this step reports on. A stable identifier, not display text. Every rule is listed under a fixed id, the name-based and family rules included. The one exception is the hybrid rule, whose id is composed during evaluation: it is listed as PQC-HYBRID on a step it does not decide, and as PQC-HYBRID- followed by the deciding family\'s rule id on the step it decides
     * @type {string}
     * @memberof PqcExplanationStepDto
     */
    ruleId: string;
    /**
     * What the rule checks, in a few words for display beside the rule id, such as \"Certified key\" or \"Symmetric key size\". The same for every asset that walks the rule
     * @type {string}
     * @memberof PqcExplanationStepDto
     */
    title: string;
    /**
     * What the rule did for this asset
     * @type {PqcExplanationStepOutcome}
     * @memberof PqcExplanationStepDto
     */
    outcome: PqcExplanationStepOutcome;
    /**
     * The verdict the rule yields
     * @type {PqcVerdict}
     * @memberof PqcExplanationStepDto
     */
    verdict?: PqcVerdict;
    /**
     * Why the rule did what it did, in plain words
     * @type {string}
     * @memberof PqcExplanationStepDto
     */
    message: string;
    /**
     * Values of the asset properties this rule read and, on a resolved step, the reference it decided by. Values are strings, numbers, booleans or lists of strings, never nested objects
     * @type {{ [key: string]: any; }}
     * @memberof PqcExplanationStepDto
     */
    evaluatedFields?: { [key: string]: any };
    /**
     * The inventory asset whose stored verdict this rule carried over
     * @type {PqcReferencedAssetDto}
     * @memberof PqcExplanationStepDto
     */
    referencedAsset?: PqcReferencedAssetDto;
}
