// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CryptographicAssetType } from './';

/**
 * An inventory asset whose stored verdict was carried over into another asset\'s: the key a certificate certifies or the algorithm it is signed with, whichever is weaker, or the weakest algorithm a protocol\'s cipher suites name. The uuid is the one recorded when the verdict was decided; visible says whether the reader may read that asset\'s detail now. name and type are read from it as currently stored, and are absent when visible is false; type is also absent for an asset declaring no CycloneDX asset type, and name for one with no name to serve
 * @export
 * @interface PqcReferencedAssetDto
 */
export interface PqcReferencedAssetDto {
    /**
     * UUID of the referenced inventory asset, as recorded when the verdict was decided
     * @type {string}
     * @memberof PqcReferencedAssetDto
     */
    uuid: string;
    /**
     * True when the referenced asset is still in the inventory and the reader may read its detail; false when it has been removed or the reader\'s role does not grant detail access to it. When false, name and type are absent
     * @type {boolean}
     * @memberof PqcReferencedAssetDto
     */
    visible: boolean;
    /**
     * Display name of the referenced asset, so a link can be labelled without a second read; absent when visible is false, or when the asset has no name to serve
     * @type {string}
     * @memberof PqcReferencedAssetDto
     */
    name?: string;
    /**
     * Type of the referenced asset
     * @type {CryptographicAssetType}
     * @memberof PqcReferencedAssetDto
     */
    type?: CryptographicAssetType;
}
