// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BrandingTheme } from './';

/**
 * @export
 * @interface PublicBrandingDto
 */
export interface PublicBrandingDto {
    /**
     * Whether the operator has configured branding. When false, every other field is null and a client applies the platform\'s own themes.
     * @type {boolean}
     * @memberof PublicBrandingDto
     */
    configured: boolean;
    /**
     * Primary brand color, used for the header and for solid interactive elements
     * @type {string}
     * @memberof PublicBrandingDto
     */
    primaryColor?: string;
    /**
     * Secondary brand color, used as an accent
     * @type {string}
     * @memberof PublicBrandingDto
     */
    secondaryColor?: string;
    /**
     * Tertiary brand color, used as an additional accent
     * @type {string}
     * @memberof PublicBrandingDto
     */
    tertiaryColor?: string;
    /**
     * Page background color of the branded theme
     * @type {string}
     * @memberof PublicBrandingDto
     */
    backgroundColor?: string;
    /**
     * Body text color of the branded theme
     * @type {string}
     * @memberof PublicBrandingDto
     */
    textColor?: string;
    /**
     * Logo shown by the branded light theme, as a base64 data URI
     * @type {string}
     * @memberof PublicBrandingDto
     */
    lightLogo?: string;
    /**
     * Logo shown by the branded dark theme, as a base64 data URI
     * @type {string}
     * @memberof PublicBrandingDto
     */
    darkLogo?: string;
    /**
     * Branded theme applied when the user has expressed no preference of their own
     * @type {BrandingTheme}
     * @memberof PublicBrandingDto
     */
    defaultTheme?: BrandingTheme;
}
