// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    AttributeContentType,
    AttributeType,
    AttributeVersion,
    BaseAttributeContentDtoV2,
    NameAndUuidDto,
    ResponseMetadataV2,
    ResponseMetadataV3,
} from './';

/**
 * @type ResponseMetadataDto
 * Request attribute to send attribute content for object
 * @export
 */
export type ResponseMetadataDto = ResponseMetadataV2 | ResponseMetadataV3;
