// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SchedulerJobExecutionStatus } from './';

/**
 * @export
 * @interface ScheduledJobDetailDto
 */
export interface ScheduledJobDetailDto {
    /**
     * UUID of the scheduled job
     * @type {string}
     * @memberof ScheduledJobDetailDto
     */
    uuid: string;
    /**
     * Name of the scheduled job
     * @type {string}
     * @memberof ScheduledJobDetailDto
     */
    jobName: string;
    /**
     * Type of scheduled job (job processor name)
     * @type {string}
     * @memberof ScheduledJobDetailDto
     */
    jobType: string;
    /**
     * CRON expression representing configuration of pattern how to run scheduled job
     * @type {string}
     * @memberof ScheduledJobDetailDto
     */
    cronExpression: string;
    /**
     * Status of the scheduled job. True = Enabled, False = Disabled
     * @type {boolean}
     * @memberof ScheduledJobDetailDto
     */
    enabled: boolean;
    /**
     * Is scheduled job triggered only once
     * @type {boolean}
     * @memberof ScheduledJobDetailDto
     */
    oneTime: boolean;
    /**
     * Is system scheduled job
     * @type {boolean}
     * @memberof ScheduledJobDetailDto
     */
    system: boolean;
    /**
     * Execution status of last job triggered task
     * @type {SchedulerJobExecutionStatus}
     * @memberof ScheduledJobDetailDto
     */
    lastExecutionStatus: SchedulerJobExecutionStatus;
    /**
     * Time at which the job is next due to run, projected from its stored CRON expression -- not an observed value read back from the scheduler, so it does not confirm the scheduler still holds a live trigger for this job. Absent when the job is disabled, when it is a one-time job whose run has succeeded, or when its CRON expression yields no further run. Evaluated in core\'s JVM default timezone; assumes this matches the timezone the scheduler service had when the job\'s trigger was created -- if the two differ, this value can be off by the difference between them.
     * @type {string}
     * @memberof ScheduledJobDetailDto
     */
    nextFireTime?: string;
    /**
     * @type {string}
     * @memberof ScheduledJobDetailDto
     */
    userUuid?: string;
    /**
     * @type {any}
     * @memberof ScheduledJobDetailDto
     */
    objectData?: any | null;
}
