// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ScheduledJobScheduleState, SchedulerJobExecutionStatus } from './';

/**
 * @export
 * @interface ScheduledJobDto
 */
export interface ScheduledJobDto {
    /**
     * UUID of the scheduled job
     * @type {string}
     * @memberof ScheduledJobDto
     */
    uuid: string;
    /**
     * Name of the scheduled job
     * @type {string}
     * @memberof ScheduledJobDto
     */
    jobName: string;
    /**
     * Type of scheduled job (job processor name)
     * @type {string}
     * @memberof ScheduledJobDto
     */
    jobType: string;
    /**
     * CRON expression representing configuration of pattern how to run scheduled job
     * @type {string}
     * @memberof ScheduledJobDto
     */
    cronExpression: string;
    /**
     * Status of the scheduled job. True = Enabled, False = Disabled
     * @type {boolean}
     * @memberof ScheduledJobDto
     */
    enabled: boolean;
    /**
     * Is scheduled job triggered only once
     * @type {boolean}
     * @memberof ScheduledJobDto
     */
    oneTime: boolean;
    /**
     * Is system scheduled job
     * @type {boolean}
     * @memberof ScheduledJobDto
     */
    system: boolean;
    /**
     * Execution status of last job triggered task
     * @type {SchedulerJobExecutionStatus}
     * @memberof ScheduledJobDto
     */
    lastExecutionStatus: SchedulerJobExecutionStatus;
    /**
     * State of the job\'s trigger as the scheduler service reported it for this response. \'scheduled\': the scheduler holds a live trigger. \'paused\': the trigger is paused, which is what disabling the job does. \'blocked\': the trigger waits for a run still in progress. \'error\': the scheduler could not fire the trigger and stopped trying. \'complete\': the trigger has no fire time left. \'notScheduled\': the scheduler holds no trigger for this job -- the normal end of a one-time job once its run has succeeded, since the platform then removes it from the scheduler; any other job will not fire until it is registered again. \'unknown\': the scheduler could not be read for this response, or it reported no state for the trigger (a scheduler that predates this field); nextFireTime and previousFireTime are then absent.
     * @type {ScheduledJobScheduleState}
     * @memberof ScheduledJobDto
     */
    scheduleState: ScheduledJobScheduleState;
    /**
     * When the scheduler will next fire the job: the fire time it holds for the job\'s trigger, computed from the trigger\'s own schedule, not projected from the stored CRON expression. Absent while the schedule state is \'paused\', \'error\', \'notScheduled\' or \'unknown\', and when the trigger has no further fire time. While the state is \'scheduled\', the scheduler is not firing if this value is in the past or previousFireTime is earlier than the last time the schedule should have fired before now. Check both: a scheduler that is alive but stuck keeps moving this value to about now.
     * @type {string}
     * @memberof ScheduledJobDto
     */
    nextFireTime?: string;
    /**
     * When the scheduler last fired the job, by the scheduler\'s clock. Absent while the schedule state is \'notScheduled\' or \'unknown\', and until the trigger has fired once. A firing newer than both lastExecutionStartTime and lastSkippedAt by more than the clock difference between the scheduler and the platform has not reached the platform, which stamps those after the firing it acts on.
     * @type {string}
     * @memberof ScheduledJobDto
     */
    previousFireTime?: string;
    /**
     * When the last recorded run of the job started, by the platform\'s own clock as it began the run, after the scheduler fired it; absent while the job has no run in its history.
     * @type {string}
     * @memberof ScheduledJobDto
     */
    lastExecutionStartTime?: string;
    /**
     * When the job last ran and declined the run -- nothing to do, or a condition it could not proceed under -- by the platform\'s own clock as it recorded the skip, after the scheduler fired the run. A declined run leaves no history row; this is what shows the job is alive. Absent until the job has declined a run.
     * @type {string}
     * @memberof ScheduledJobDto
     */
    lastSkippedAt?: string;
    /**
     * Why the run at lastSkippedAt was declined, in the task\'s own words; absent with it.
     * @type {string}
     * @memberof ScheduledJobDto
     */
    lastSkipReason?: string;
}
