// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AttributeContentType, FilterConditionOperator, FilterFieldType, PlatformEnum } from './';

/**
 * @export
 * @interface SearchFieldDataDto
 */
export interface SearchFieldDataDto {
    /**
     * Identifier of field to search
     * @type {string}
     * @memberof SearchFieldDataDto
     */
    fieldIdentifier: string;
    /**
     * Label for the field
     * @type {string}
     * @memberof SearchFieldDataDto
     */
    fieldLabel: string;
    /**
     * Type of the field
     * @type {FilterFieldType}
     * @memberof SearchFieldDataDto
     */
    type: FilterFieldType;
    /**
     * List of available conditions for the field
     * @type {Array<FilterConditionOperator>}
     * @memberof SearchFieldDataDto
     */
    conditions: Array<FilterConditionOperator>;
    /**
     * Platform enum of the field values
     * @type {PlatformEnum}
     * @memberof SearchFieldDataDto
     */
    platformEnum?: PlatformEnum;
    /**
     * Attribute filter field content type
     * @type {AttributeContentType}
     * @memberof SearchFieldDataDto
     */
    attributeContentType?: AttributeContentType;
    /**
     * @type {any}
     * @memberof SearchFieldDataDto
     */
    value?: any | null;
    /**
     * Multivalue flag. true = yes, false = no
     * @type {boolean}
     * @memberof SearchFieldDataDto
     */
    multiValue?: boolean;
    /**
     * Whether the field may be requested as a column of the listing. true = yes, false = no
     * @type {boolean}
     * @memberof SearchFieldDataDto
     */
    displayable?: boolean;
    /**
     * Whether the listing may be ordered by the field. true = yes, false = no
     * @type {boolean}
     * @memberof SearchFieldDataDto
     */
    sortable?: boolean;
}
