// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SearchColumnRequestDto, SearchFilterRequestDto, SearchSortRequestDto } from './';

/**
 * @export
 * @interface SearchRequestDto
 */
export interface SearchRequestDto {
    /**
     * Certificate filter input
     * @type {Array<SearchFilterRequestDto>}
     * @memberof SearchRequestDto
     */
    filters?: Array<SearchFilterRequestDto>;
    /**
     * Number of entries per page
     * @type {number}
     * @memberof SearchRequestDto
     */
    itemsPerPage?: number;
    /**
     * Page number for the request
     * @type {number}
     * @memberof SearchRequestDto
     */
    pageNumber?: number;
    /**
     * Ordering of the whole result set. When omitted, the endpoint\'s own default ordering applies, unchanged from before this field existed.
     * @type {SearchSortRequestDto}
     * @memberof SearchRequestDto
     */
    sort?: SearchSortRequestDto;
    /**
     * Fields to return as columns. When omitted, the response carries the endpoint\'s full default shape, unchanged from before this field existed. Requesting attribute-sourced fields adds their values to each returned object.
     * @type {Array<SearchColumnRequestDto>}
     * @memberof SearchRequestDto
     */
    columns?: Array<SearchColumnRequestDto>;
}
