// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Level a signature has reached, ordered from SIGNED up to ARCHIVAL with each level containing the one before it
 * @export
 * @enum {string}
 */
export enum SignatureLevel {
    Signed = 'signed',
    Timestamped = 'timestamped',
    LongTerm = 'long_term',
    Archival = 'archival',
}
