// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * How a signing operation was initiated. Some values name a client protocol that a Signing Profile can enable; others record an invocation the platform makes on its own and can never be enabled.
 * @export
 * @enum {string}
 */
export enum SigningProtocol {
    CscApi = 'csc_api',
    Tsp = 'tsp',
    InternalTsa = 'internal_tsa',
}
