// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InternalTimestampSourceDto, NameAndUuidDto, TimestampSourceType } from './';

/**
 * @type TimestampSourceDto
 * Source of the timestamps a content-signing profile embeds, as currently configured on the profile. The required type property is the discriminator selecting the source.
 * @export
 */
export type TimestampSourceDto = InternalTimestampSourceDto;
