// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ResponseAttribute } from './';
import type { SimplifiedSigningProfileDto } from './';

/**
 * TSP Profile details
 * @export
 * @interface TspProfileDto
 */
export interface TspProfileDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof TspProfileDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof TspProfileDto
     */
    name: string;
    /**
     * Description
     * @type {string}
     * @memberof TspProfileDto
     */
    description?: string;
    /**
     * Whether the TSP Profile is enabled
     * @type {boolean}
     * @memberof TspProfileDto
     */
    enabled: boolean;
    /**
     * TSP signing URL
     * @type {string}
     * @memberof TspProfileDto
     */
    signingUrl?: string;
    /**
     * Default signing profile
     * @type {SimplifiedSigningProfileDto}
     * @memberof TspProfileDto
     */
    defaultSigningProfile?: SimplifiedSigningProfileDto;
    /**
     * List of Custom Attributes
     * @type {Array<ResponseAttribute>}
     * @memberof TspProfileDto
     */
    customAttributes?: Array<ResponseAttribute>;
}
