// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SimplifiedSigningProfileDto } from './';

/**
 * TSP Profile list item
 * @export
 * @interface TspProfileListDto
 */
export interface TspProfileListDto {
    /**
     * Object identifier
     * @type {string}
     * @memberof TspProfileListDto
     */
    uuid: string;
    /**
     * Object Name
     * @type {string}
     * @memberof TspProfileListDto
     */
    name: string;
    /**
     * Description
     * @type {string}
     * @memberof TspProfileListDto
     */
    description?: string;
    /**
     * Whether the TSP Profile is enabled
     * @type {boolean}
     * @memberof TspProfileListDto
     */
    enabled: boolean;
    /**
     * Default signing profile
     * @type {SimplifiedSigningProfileDto}
     * @memberof TspProfileListDto
     */
    defaultSigningProfile?: SimplifiedSigningProfileDto;
}
