// tslint:disable
/**
 * Core API
 * REST API for CZERTAINLY Core
 *
 * The version of the OpenAPI document: 2.17.1-SNAPSHOT
 * Contact: info@otilm.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestAttribute } from './';

/**
 * TSP Profile create/update request
 * @export
 * @interface TspProfileRequestDto
 */
export interface TspProfileRequestDto {
    /**
     * Object Name
     * @type {string}
     * @memberof TspProfileRequestDto
     */
    name: string;
    /**
     * Description
     * @type {string}
     * @memberof TspProfileRequestDto
     */
    description?: string;
    /**
     * UUID of the default signing profile
     * @type {string}
     * @memberof TspProfileRequestDto
     */
    defaultSigningProfileUuid?: string;
    /**
     * List of Custom Attributes
     * @type {Array<RequestAttribute>}
     * @memberof TspProfileRequestDto
     */
    customAttributes?: Array<RequestAttribute>;
}
