// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UtilsSettingsDto
 */
export interface UtilsSettingsDto {
    /**
     * URL of the Util Service
     * @type {string}
     * @memberof UtilsSettingsDto
     */
    utilsServiceUrl?: string;
    /**
     * URL of the CBOM Repository
     * @type {string}
     * @memberof UtilsSettingsDto
     */
    cbomRepositoryUrl?: string;
    /**
     * How far before the start of the last successful CBOM sync run each run re-lists the CBOM Repository, in seconds. It should cover the clock skew between the platform and the repository\'s object store plus the longest upload. 0 re-lists only from the start of the last run. Entries listed twice are stored once
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncOverlapSeconds?: number;
    /**
     * How many later CBOM sync runs retry a repository entry that could not be stored before it is given up on as permanently skipped; 0 gives an entry up at its first failure
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncSkippedRetryRuns?: number;
    /**
     * How many CBOMs one sync run ingests cryptographic assets from, beyond the entries the run has just stored: earlier failures, interrupted ingests and CBOMs uploaded through the platform API. 0 turns that catch-up off
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncMaxIngestDocuments?: number;
}
