// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @export
 * @interface UtilsSettingsDto
 */
export interface UtilsSettingsDto {
    /**
     * URL of the Util Service
     * @type {string}
     * @memberof UtilsSettingsDto
     */
    utilsServiceUrl?: string;
    /**
     * URL of the CBOM Repository
     * @type {string}
     * @memberof UtilsSettingsDto
     */
    cbomRepositoryUrl?: string;
    /**
     * How far before the start of the last successful CBOM sync run each run re-lists the CBOM Repository, in seconds. It should cover the clock skew between the platform and the repository\'s object store plus the longest upload. 0 re-lists only from the start of the last run. Entries listed twice are stored once
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncOverlapSeconds?: number;
    /**
     * How many later CBOM sync runs retry a repository entry that could not be stored before it is given up on as permanently skipped; 0 gives an entry up at its first failure
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncSkippedRetryRuns?: number;
    /**
     * How many CBOMs one sync run ingests cryptographic assets from, beyond the entries the run has just stored: earlier failures, interrupted ingests and CBOMs uploaded through the platform API. 0 turns that catch-up off
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncMaxIngestDocuments?: number;
    /**
     * How many days after its last attempt a CBOM Repository entry the sync gave up on (permanently skipped) stays listed before its record is removed; an entry still being retried is kept whatever its age. At least one day: a retention of nothing would remove a write-off as it lands
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncSkipRetentionDays?: number;
    /**
     * How many entries one page of the CBOM Repository listing carries, sent as the search `limit`. Pages are followed through the `Link rel=\"next\"` header, so this bounds one request rather than one run
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncPageSize?: number;
    /**
     * Whether a sync run ingests cryptographic assets at all. Off covers both discovery paths -- the ingest of a document the run has just stored and the catch-up over the documents that still owe one -- and leaves each CBOM exactly as it was found, so turning it back on resumes rather than repairs
     * @type {boolean}
     * @memberof UtilsSettingsDto
     */
    cbomSyncAssetIngestEnabled?: boolean;
    /**
     * How many cryptographic assets one ingest transaction writes before committing, and the page size the withdrawal of a CBOM\'s assets walks. It bounds how long one transaction holds its locks, not how much work a run does
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncAssetBatchSize?: number;
    /**
     * How long a CBOM whose asset ingest is in progress or has failed is left alone before a run offers it again, in seconds. Measured from the start of the attempt, so it has to exceed the longest single document the deployment expects to ingest. 0 offers it to the very next run
     * @type {number}
     * @memberof UtilsSettingsDto
     */
    cbomSyncIngestRetryAfterSeconds?: number;
}
