// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    DigestAlgorithm,
    DocumentSigningWorkflowDto,
    NameAndUuidDto,
    RawSigningWorkflowDto,
    ResponseAttribute,
    SigningWorkflowType,
    TimeQualityConfigurationDto,
    TimestampingWorkflowDto,
} from './';

/**
 * @type WorkflowInterface
 * Workflow configuration specific to the signing workflow type, embedded in a Signing Profile
 * @export
 */
export type WorkflowInterface = DocumentSigningWorkflowDto | RawSigningWorkflowDto | TimestampingWorkflowDto;
