// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
    DigestAlgorithm,
    DocumentSigningWorkflowRequestDto,
    RawSigningWorkflowRequestDto,
    RequestAttribute,
    SigningWorkflowType,
    TimestampingWorkflowRequestDto,
} from './';

/**
 * @type WorkflowRequestInterface
 * Workflow configuration request specific to the signing workflow type
 * @export
 */
export type WorkflowRequestInterface = DocumentSigningWorkflowRequestDto | RawSigningWorkflowRequestDto | TimestampingWorkflowRequestDto;
