// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts } from '../runtime';
import type { ErrorMessageDto, PublicBrandingDto } from '../models';

/**
 * no description
 */
export class BrandingApi extends BaseAPI {
    /**
     * Get branding available to unauthenticated clients
     */
    getBranding(): Observable<PublicBrandingDto>;
    getBranding(opts?: OperationOpts): Observable<AjaxResponse<PublicBrandingDto>>;
    getBranding(opts?: OperationOpts): Observable<PublicBrandingDto | AjaxResponse<PublicBrandingDto>> {
        return this.request<PublicBrandingDto>(
            {
                url: '/v1/branding',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }
}
