// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    BulkActionMessageDto,
    CbomDetailDto,
    CbomDto,
    CbomSyncSkipDto,
    CbomUploadRequestDto,
    ErrorMessageDto,
    PaginationResponseDtoCbomDto,
    PaginationResponseDtoCbomSyncSkipDto,
    SearchFieldDataByGroupDto,
    SearchRequestDto,
} from '../models';

export interface BulkDeleteCbomRequest {
    requestBody: Array<string>;
}

export interface DeleteCbomRequest {
    uuid: string;
}

export interface GetCbomDetailRequest {
    uuid: string;
}

export interface ListCbomSyncSkipsRequest {
    searchRequestDto: SearchRequestDto;
}

export interface ListCbomVersionsRequest {
    uuid: string;
}

export interface ListCbomsRequest {
    searchRequestDto: SearchRequestDto;
}

export interface RetryCbomSyncSkipRequest {
    uuid: string;
}

export interface UploadCbomRequest {
    cbomUploadRequestDto: CbomUploadRequestDto;
}

/**
 * no description
 */
export class CBOMManagementApi extends BaseAPI {
    /**
     * Delete multiple CBOM entries
     */
    bulkDeleteCbom({ requestBody }: BulkDeleteCbomRequest): Observable<Array<BulkActionMessageDto>>;
    bulkDeleteCbom({ requestBody }: BulkDeleteCbomRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<BulkActionMessageDto>>>;
    bulkDeleteCbom(
        { requestBody }: BulkDeleteCbomRequest,
        opts?: OperationOpts,
    ): Observable<Array<BulkActionMessageDto> | AjaxResponse<Array<BulkActionMessageDto>>> {
        throwIfNullOrUndefined(requestBody, 'requestBody', 'bulkDeleteCbom');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<Array<BulkActionMessageDto>>(
            {
                url: '/v1/cboms',
                method: 'DELETE',
                headers,
                body: requestBody,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Delete CBOM entry
     */
    deleteCbom({ uuid }: DeleteCbomRequest): Observable<void>;
    deleteCbom({ uuid }: DeleteCbomRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    deleteCbom({ uuid }: DeleteCbomRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteCbom');

        return this.request<void>(
            {
                url: '/v1/cboms/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * CBOM detail
     */
    getCbomDetail({ uuid }: GetCbomDetailRequest): Observable<CbomDetailDto>;
    getCbomDetail({ uuid }: GetCbomDetailRequest, opts?: OperationOpts): Observable<AjaxResponse<CbomDetailDto>>;
    getCbomDetail({ uuid }: GetCbomDetailRequest, opts?: OperationOpts): Observable<CbomDetailDto | AjaxResponse<CbomDetailDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getCbomDetail');

        return this.request<CbomDetailDto>(
            {
                url: '/v1/cboms/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Besides the conditions a field may be filtered with, each field reports whether it can serve as a configurable column of the listing: `displayable` marks the fields that may be named in `columns`, and `sortable` those the listing may be ordered by. A field that reports neither flag is filter-only, so an absent flag is to be read as `false` rather than as unknown.  Both flags are answered per field, and that answer is authoritative for attribute-sourced fields as much as for property ones: whether a given attribute may be ordered on depends on the resource and is reported here rather than assumed. A field that may be shown but not ordered on reports `displayable` without `sortable`.
     * Get Cbom searchable fields information
     */
    getCbomSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>;
    getCbomSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>;
    getCbomSearchableFields(
        opts?: OperationOpts,
    ): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>(
            {
                url: '/v1/cboms/search',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * The fields the list of entries the sync could not store may be filtered or ordered by. Each carries the conditions it accepts and, where the list may be ordered by it, `sortable`; a field that is an ordering key only carries `sortable` with an empty list of conditions, so every identifier `sort` accepts can be read from here rather than from prose. The rows have a fixed shape, so no field is offered as a column: `displayable` is never set.
     * Get the searchable fields of the entries the sync could not store
     */
    getCbomSyncSkipSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>;
    getCbomSyncSkipSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>;
    getCbomSyncSkipSearchableFields(
        opts?: OperationOpts,
    ): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>(
            {
                url: '/v1/cboms/syncSkips/search',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * The documents the header sync found in the CBOM Repository listing but could not turn into a CBOM record: the document could not be read, or storing its header failed. Later sync runs retry an entry until its retry budget (the platform setting `cbomSyncSkippedRetryRuns`) is spent; it is then kept as permanently skipped until the retention (`cbomSyncSkipRetentionDays`) after its last attempt runs out. Each row carries the reason of the last failure, worded for an operator. An entry leaves the list on the run that manages to store its document, or finds the document gone from the repository; nothing else removes one but the retention and an operator deleting the CBOM.  By default the list is ordered newest failure first: last attempt descending, then UUID ascending. `sort` reorders it and names its field by source `property` and identifier `CBOM_SYNC_SKIP_LAST_ATTEMPT_AT`, `CBOM_SYNC_SKIP_FIRST_SKIPPED_AT`, `CBOM_SYNC_SKIP_ATTEMPTS` or `CBOM_SYNC_SKIP_SERIAL_NUMBER`. `filters` may use `CBOM_SYNC_SKIP_STATE` (equals, not equals) and `CBOM_SYNC_SKIP_SERIAL_NUMBER` (equals, not equals, contains, not contains, starts with), both of source `property`. The searchable-fields operation of this list publishes all of them, the three that are ordering keys only among them. The rows have a fixed shape: no field is offered as a column, and `columns` is accepted and ignored.
     * List the CBOM Repository entries the sync could not store
     */
    listCbomSyncSkips({ searchRequestDto }: ListCbomSyncSkipsRequest): Observable<PaginationResponseDtoCbomSyncSkipDto>;
    listCbomSyncSkips(
        { searchRequestDto }: ListCbomSyncSkipsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoCbomSyncSkipDto>>;
    listCbomSyncSkips(
        { searchRequestDto }: ListCbomSyncSkipsRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoCbomSyncSkipDto | AjaxResponse<PaginationResponseDtoCbomSyncSkipDto>> {
        throwIfNullOrUndefined(searchRequestDto, 'searchRequestDto', 'listCbomSyncSkips');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaginationResponseDtoCbomSyncSkipDto>(
            {
                url: '/v1/cboms/syncSkips',
                method: 'POST',
                headers,
                body: searchRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * List CBOM versions
     */
    listCbomVersions({ uuid }: ListCbomVersionsRequest): Observable<Array<CbomDto>>;
    listCbomVersions({ uuid }: ListCbomVersionsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<CbomDto>>>;
    listCbomVersions({ uuid }: ListCbomVersionsRequest, opts?: OperationOpts): Observable<Array<CbomDto> | AjaxResponse<Array<CbomDto>>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'listCbomVersions');

        return this.request<Array<CbomDto>>(
            {
                url: '/v1/cboms/{uuid}/versions'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Ordering and columns address a field by its source together with its identifier, because an identifier is unique only within its source. Both halves, and which fields may be shown or ordered on, come from the searchable-fields operation of this resource.  `sort` orders the whole result set before it is paged, so paging walks the sorted set rather than sorting one page at a time; only fields the catalogue marks `sortable` may be used. `columns` names the fields the caller means to display, and only fields the catalogue marks `displayable` may be named. It does not narrow the response: every listing object comes back whole, and naming a property field asks for nothing extra because the object already carries it. Naming an attribute-sourced field is what has an effect, described below.  A request that carries neither `sort` nor `columns` is answered exactly as it was before the two fields existed: the endpoint\'s own default ordering, the full default shape of every object, and no `attributeValues` member. A caller written against the previous contract therefore needs no change.  Requesting attribute-sourced columns adds an `attributeValues` member to each returned object, keyed by field source and then by field identifier. A field the object holds no value for is absent rather than empty, and a multi-valued attribute arrives in its stored `item_order`.
     * List CBOMs
     */
    listCboms({ searchRequestDto }: ListCbomsRequest): Observable<PaginationResponseDtoCbomDto>;
    listCboms({ searchRequestDto }: ListCbomsRequest, opts?: OperationOpts): Observable<AjaxResponse<PaginationResponseDtoCbomDto>>;
    listCboms(
        { searchRequestDto }: ListCbomsRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoCbomDto | AjaxResponse<PaginationResponseDtoCbomDto>> {
        throwIfNullOrUndefined(searchRequestDto, 'searchRequestDto', 'listCboms');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaginationResponseDtoCbomDto>(
            {
                url: '/v1/cboms',
                method: 'POST',
                headers,
                body: searchRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Puts a permanently skipped entry back to retrying with a full budget: `state` becomes `retrying` and `attempts` becomes 0, while `reason`, `firstSkippedAt` and `lastAttemptAt` keep the values of the last attempt until the next sync run tries the entry. An entry that is still retrying is left as it is. Answers with the row as it now stands.  The retry does not make the entry permanent: if the document still cannot be stored, the new budget is spent like the first one and the entry is written off again, and the retention then runs from that last attempt.
     * Ask the sync to try a permanently skipped entry again
     */
    retryCbomSyncSkip({ uuid }: RetryCbomSyncSkipRequest): Observable<CbomSyncSkipDto>;
    retryCbomSyncSkip({ uuid }: RetryCbomSyncSkipRequest, opts?: OperationOpts): Observable<AjaxResponse<CbomSyncSkipDto>>;
    retryCbomSyncSkip(
        { uuid }: RetryCbomSyncSkipRequest,
        opts?: OperationOpts,
    ): Observable<CbomSyncSkipDto | AjaxResponse<CbomSyncSkipDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'retryCbomSyncSkip');

        return this.request<CbomSyncSkipDto>(
            {
                url: '/v1/cboms/syncSkips/{uuid}/retry'.replace('{uuid}', encodeURI(uuid)),
                method: 'POST',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Sync CBOMs
     */
    sync(): Observable<void>;
    sync(opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    sync(opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        return this.request<void>(
            {
                url: '/v1/cboms/sync',
                method: 'POST',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Upload CBOM
     */
    uploadCbom({ cbomUploadRequestDto }: UploadCbomRequest): Observable<CbomDto>;
    uploadCbom({ cbomUploadRequestDto }: UploadCbomRequest, opts?: OperationOpts): Observable<AjaxResponse<CbomDto>>;
    uploadCbom({ cbomUploadRequestDto }: UploadCbomRequest, opts?: OperationOpts): Observable<CbomDto | AjaxResponse<CbomDto>> {
        throwIfNullOrUndefined(cbomUploadRequestDto, 'cbomUploadRequestDto', 'uploadCbom');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CbomDto>(
            {
                url: '/v1/cboms/upload',
                method: 'POST',
                headers,
                body: cbomUploadRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
