// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    AvailableOperations,
    BaseAttributeDto,
    CancelPendingCertificateRequestDto,
    CertificateDetailDto,
    ClientCertificateDataResponseDto,
    ClientCertificateIssueRequestDto,
    ClientCertificateRegistrationRequest,
    ClientCertificateRekeyRequestDto,
    ClientCertificateRenewRequestDto,
    ClientCertificateRevocationDto,
    ErrorMessageDto,
    ManuallyIssueCertificateRequestDto,
    RequestAttribute,
} from '../models';

export interface CancelPendingCertificateOperationRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    cancelPendingCertificateRequestDto?: CancelPendingCertificateRequestDto;
}

export interface IssueCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    clientCertificateIssueRequestDto: ClientCertificateIssueRequestDto;
}

export interface IssueExistingCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    clientCertificateIssueRequestDto?: ClientCertificateIssueRequestDto;
}

export interface ListAvailableOperationsRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ListIdentifyCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ListIssueCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ListRegisterCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ListRenewCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ListRevokeCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
}

export interface ManuallyConfirmRevokeRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
}

export interface ManuallyIssueCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    manuallyIssueCertificateRequestDto: ManuallyIssueCertificateRequestDto;
}

export interface RegisterCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    clientCertificateRegistrationRequest: ClientCertificateRegistrationRequest;
}

export interface RekeyCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    clientCertificateRekeyRequestDto: ClientCertificateRekeyRequestDto;
}

export interface RenewCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    clientCertificateRenewRequestDto: ClientCertificateRenewRequestDto;
}

export interface RevokeCertificateRequest {
    authorityUuid: string;
    raProfileUuid: string;
    certificateUuid: string;
    clientCertificateRevocationDto: ClientCertificateRevocationDto;
}

export interface ValidateIssueCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
    requestAttribute: Array<RequestAttribute>;
}

export interface ValidateRevokeCertificateAttributesRequest {
    authorityUuid: string;
    raProfileUuid: string;
    requestAttribute: Array<RequestAttribute>;
}

/**
 * no description
 */
export class ClientOperationsV2Api extends BaseAPI {
    /**
     * State-aware cancel for a certificate in `PENDING_ISSUE` or `PENDING_REVOKE`:  - `PENDING_ISSUE` → `FAILED` - `PENDING_REVOKE` → `ISSUED`  The optional `reason` is recorded in the certificate event history. If the underlying operation can no longer be aborted, the response is `422` and the certificate stays in its pending state; it can then be resolved by letting it complete and finalizing/confirming, or by retrying the cancel later.
     * Cancel a pending certificate operation
     */
    cancelPendingCertificateOperation({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        cancelPendingCertificateRequestDto,
    }: CancelPendingCertificateOperationRequest): Observable<CertificateDetailDto>;
    cancelPendingCertificateOperation(
        { authorityUuid, raProfileUuid, certificateUuid, cancelPendingCertificateRequestDto }: CancelPendingCertificateOperationRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateDetailDto>>;
    cancelPendingCertificateOperation(
        { authorityUuid, raProfileUuid, certificateUuid, cancelPendingCertificateRequestDto }: CancelPendingCertificateOperationRequest,
        opts?: OperationOpts,
    ): Observable<CertificateDetailDto | AjaxResponse<CertificateDetailDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'cancelPendingCertificateOperation');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'cancelPendingCertificateOperation');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'cancelPendingCertificateOperation');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CertificateDetailDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/cancel'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: cancelPendingCertificateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Submit a new certificate signing request and request issuance through this RA profile. The request is validated, persisted, and queued; issuance runs asynchronously and an approval step may run first. This response returns only the new certificate\'s UUID — it never carries the signed certificate and does not indicate completion. Track the operation through the certificate\'s state.
     * Issue certificate
     */
    issueCertificate({
        authorityUuid,
        raProfileUuid,
        clientCertificateIssueRequestDto,
    }: IssueCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    issueCertificate(
        { authorityUuid, raProfileUuid, clientCertificateIssueRequestDto }: IssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    issueCertificate(
        { authorityUuid, raProfileUuid, clientCertificateIssueRequestDto }: IssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'issueCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'issueCertificate');
        throwIfNullOrUndefined(clientCertificateIssueRequestDto, 'clientCertificateIssueRequestDto', 'issueCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'POST',
                headers,
                body: clientCertificateIssueRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Trigger issuance for an existing certificate; behaviour depends on its state: - `REQUESTED` (no body): the certificate already carries a CSR (e.g. from an ACME/SCEP/CMP   protocol layer, or after an approval/compliance cycle); issuance runs against that CSR. - `REGISTERED` (body required): a pre-registered certificate is finalized with the operator\'s   CSR (sign attributes as the RA profile requires, and the authorization secret only for   challenge-protected registrations); its registered identity (subject DN, SAN, extensions)   and connector metadata are preserved.  Queued and issued asynchronously like `issueCertificate` — track the result through the certificate\'s state.
     * Issue an existing certificate (REQUESTED or REGISTERED)
     */
    issueExistingCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        clientCertificateIssueRequestDto,
    }: IssueExistingCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    issueExistingCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateIssueRequestDto }: IssueExistingCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    issueExistingCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateIssueRequestDto }: IssueExistingCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'issueExistingCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'issueExistingCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'issueExistingCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/issue'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: clientCertificateIssueRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns per-operation support flags (issue/renew/revoke/register) including whether the platform polls for its asynchronous completion and whether each can be cancelled mid-flight. Operators use this to drive UI affordances and validate flows before invoking them.
     * List operations supported by this authority/RA profile
     */
    listAvailableOperations({ authorityUuid, raProfileUuid }: ListAvailableOperationsRequest): Observable<AvailableOperations>;
    listAvailableOperations(
        { authorityUuid, raProfileUuid }: ListAvailableOperationsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<AvailableOperations>>;
    listAvailableOperations(
        { authorityUuid, raProfileUuid }: ListAvailableOperationsRequest,
        opts?: OperationOpts,
    ): Observable<AvailableOperations | AjaxResponse<AvailableOperations>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listAvailableOperations');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listAvailableOperations');

        return this.request<AvailableOperations>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/availableOperations'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Return the list of attributes the client must populate when identifying a certificate through this RA profile. The list reflects the certificate authority\'s identify-operation attribute schema. An authority that offers no identify schema yields an empty list — this is not an error.
     * Get identify certificate attributes
     */
    listIdentifyCertificateAttributes({
        authorityUuid,
        raProfileUuid,
    }: ListIdentifyCertificateAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listIdentifyCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListIdentifyCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listIdentifyCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListIdentifyCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listIdentifyCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listIdentifyCertificateAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/identify'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Return the list of attributes the client must populate when requesting an issuance through this RA profile. The list reflects the certificate authority\'s current attribute schema.
     * Get issue certificate attributes
     */
    listIssueCertificateAttributes({
        authorityUuid,
        raProfileUuid,
    }: ListIssueCertificateAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listIssueCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listIssueCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listIssueCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listIssueCertificateAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/issue'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Return the list of attributes the client must populate when pre-registering a certificate through this RA profile. The list reflects the certificate authority\'s register-operation attribute schema.
     * Get registration attributes
     */
    listRegisterCertificateAttributes({
        authorityUuid,
        raProfileUuid,
    }: ListRegisterCertificateAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listRegisterCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRegisterCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listRegisterCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRegisterCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listRegisterCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listRegisterCertificateAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/register'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Return the list of attributes the client must populate when renewing or rekeying a certificate through this RA profile. The list reflects the certificate authority\'s renew-operation attribute schema; rekey is a renew at the authority, so the same schema applies. An authority that offers no renew schema yields an empty list — this is not an error.
     * Get renew certificate attributes
     */
    listRenewCertificateAttributes({
        authorityUuid,
        raProfileUuid,
    }: ListRenewCertificateAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listRenewCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRenewCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listRenewCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRenewCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listRenewCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listRenewCertificateAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/renew'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Return the list of attributes the client must populate when revoking a certificate through this RA profile.
     * Get revocation attributes
     */
    listRevokeCertificateAttributes({
        authorityUuid,
        raProfileUuid,
    }: ListRevokeCertificateAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid }: ListRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'listRevokeCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'listRevokeCertificateAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/revoke'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Confirm that a revoked certificate has been revoked. The certificate must be in state `PENDING_REVOKE`. The platform applies the destroy-key flag and revoke attributes from the original revoke request, transitions the certificate to `REVOKED`, and clears the data carried over from the original request.
     * Confirm an asynchronous certificate revocation
     */
    manuallyConfirmRevoke({ authorityUuid, raProfileUuid, certificateUuid }: ManuallyConfirmRevokeRequest): Observable<void>;
    manuallyConfirmRevoke(
        { authorityUuid, raProfileUuid, certificateUuid }: ManuallyConfirmRevokeRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    manuallyConfirmRevoke(
        { authorityUuid, raProfileUuid, certificateUuid }: ManuallyConfirmRevokeRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'manuallyConfirmRevoke');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'manuallyConfirmRevoke');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'manuallyConfirmRevoke');

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/revoke/confirm'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Finalize a certificate in state `PENDING_ISSUE` by uploading the issued certificate. On success it transitions to `ISSUED` and is pushed to any pre-associated locations.  Validation: the certificate request\'s public key must match the uploaded certificate (mandatory); the subject DN should match (warning only — some CAs canonicalise it); and the uploaded certificate must verify against the RA profile\'s authority (mandatory).  The body carries a Base64-encoded single certificate, optional certificate-level custom attributes, and optional identify-operation attributes for the authority\'s verification.
     * Finalize an asynchronous certificate issuance
     */
    manuallyIssueCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        manuallyIssueCertificateRequestDto,
    }: ManuallyIssueCertificateRequest): Observable<CertificateDetailDto>;
    manuallyIssueCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, manuallyIssueCertificateRequestDto }: ManuallyIssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CertificateDetailDto>>;
    manuallyIssueCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, manuallyIssueCertificateRequestDto }: ManuallyIssueCertificateRequest,
        opts?: OperationOpts,
    ): Observable<CertificateDetailDto | AjaxResponse<CertificateDetailDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'manuallyIssueCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'manuallyIssueCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'manuallyIssueCertificate');
        throwIfNullOrUndefined(manuallyIssueCertificateRequestDto, 'manuallyIssueCertificateRequestDto', 'manuallyIssueCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CertificateDetailDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/issue/finalize'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: manuallyIssueCertificateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Pre-register a certificate to be issued later; the response carries the pre-registered certificate\'s UUID and completion runs through the standard issue flow.  When the authority\'s connector supports registration (a v3 connector advertising `CERTIFICATE_REGISTRATION`), the registration is made with the upstream CA; otherwise the certificate is pre-registered at the platform level with no connector call, which does not imply a CA-side end-entity exists. Connector-side completion may be asynchronous and is tracked server-side.
     * Pre-register a certificate
     */
    registerCertificate({
        authorityUuid,
        raProfileUuid,
        clientCertificateRegistrationRequest,
    }: RegisterCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    registerCertificate(
        { authorityUuid, raProfileUuid, clientCertificateRegistrationRequest }: RegisterCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    registerCertificate(
        { authorityUuid, raProfileUuid, clientCertificateRegistrationRequest }: RegisterCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'registerCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'registerCertificate');
        throwIfNullOrUndefined(clientCertificateRegistrationRequest, 'clientCertificateRegistrationRequest', 'registerCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/register'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'POST',
                headers,
                body: clientCertificateRegistrationRequest,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Request a replacement certificate with a new key pair but the same subject and attributes as the original. Provide a new CSR with a new key pair, or select a platform-managed key pair; reusing the same key pair, or changing the subject, is rejected. Queued and issued asynchronously — track the result through the new certificate\'s state.
     * Rekey Certificate
     */
    rekeyCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        clientCertificateRekeyRequestDto,
    }: RekeyCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    rekeyCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRekeyRequestDto }: RekeyCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    rekeyCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRekeyRequestDto }: RekeyCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'rekeyCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'rekeyCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'rekeyCertificate');
        throwIfNullOrUndefined(clientCertificateRekeyRequestDto, 'clientCertificateRekeyRequestDto', 'rekeyCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/rekey'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: clientCertificateRekeyRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Renew a certificate using its existing key pair. The original certificate stays in state `ISSUED`; a new certificate is created, queued, and issued asynchronously. This response returns only the new certificate\'s UUID — track the result through its state.
     * Renew certificate
     */
    renewCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        clientCertificateRenewRequestDto,
    }: RenewCertificateRequest): Observable<ClientCertificateDataResponseDto>;
    renewCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRenewRequestDto }: RenewCertificateRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<ClientCertificateDataResponseDto>>;
    renewCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRenewRequestDto }: RenewCertificateRequest,
        opts?: OperationOpts,
    ): Observable<ClientCertificateDataResponseDto | AjaxResponse<ClientCertificateDataResponseDto>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'renewCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'renewCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'renewCertificate');
        throwIfNullOrUndefined(clientCertificateRenewRequestDto, 'clientCertificateRenewRequestDto', 'renewCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ClientCertificateDataResponseDto>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/renew'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: clientCertificateRenewRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Revoke a certificate currently in state `ISSUED`. The request is accepted and queued; revocation runs through the authority and an approval step may run first. This response is returned before the authority call completes, so it does not indicate completion — the certificate ends in `REVOKED` if the authority completes the revocation immediately, or `PENDING_REVOKE` if completion is deferred and later confirmed. Track the result through its state.
     * Revoke certificate
     */
    revokeCertificate({
        authorityUuid,
        raProfileUuid,
        certificateUuid,
        clientCertificateRevocationDto,
    }: RevokeCertificateRequest): Observable<void>;
    revokeCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRevocationDto }: RevokeCertificateRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    revokeCertificate(
        { authorityUuid, raProfileUuid, certificateUuid, clientCertificateRevocationDto }: RevokeCertificateRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'revokeCertificate');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'revokeCertificate');
        throwIfNullOrUndefined(certificateUuid, 'certificateUuid', 'revokeCertificate');
        throwIfNullOrUndefined(clientCertificateRevocationDto, 'clientCertificateRevocationDto', 'revokeCertificate');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/certificates/{certificateUuid}/revoke'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid))
                    .replace('{certificateUuid}', encodeURI(certificateUuid)),
                method: 'POST',
                headers,
                body: clientCertificateRevocationDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Validate a candidate set of issuance attributes against this RA profile\'s schema before submitting an issuance request. Returns 422 with a list of error messages when the attributes are not acceptable.
     * Validate issue certificate attributes
     */
    validateIssueCertificateAttributes({
        authorityUuid,
        raProfileUuid,
        requestAttribute,
    }: ValidateIssueCertificateAttributesRequest): Observable<void>;
    validateIssueCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    validateIssueCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateIssueCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'validateIssueCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'validateIssueCertificateAttributes');
        throwIfNullOrUndefined(requestAttribute, 'requestAttribute', 'validateIssueCertificateAttributes');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/issue/validate'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'POST',
                headers,
                body: requestAttribute,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Validate a candidate set of revocation attributes against this RA profile\'s schema before submitting a revocation request.
     * Validate revocation attributes
     */
    validateRevokeCertificateAttributes({
        authorityUuid,
        raProfileUuid,
        requestAttribute,
    }: ValidateRevokeCertificateAttributesRequest): Observable<void>;
    validateRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>>;
    validateRevokeCertificateAttributes(
        { authorityUuid, raProfileUuid, requestAttribute }: ValidateRevokeCertificateAttributesRequest,
        opts?: OperationOpts,
    ): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(authorityUuid, 'authorityUuid', 'validateRevokeCertificateAttributes');
        throwIfNullOrUndefined(raProfileUuid, 'raProfileUuid', 'validateRevokeCertificateAttributes');
        throwIfNullOrUndefined(requestAttribute, 'requestAttribute', 'validateRevokeCertificateAttributes');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<void>(
            {
                url: '/v2/operations/authorities/{authorityUuid}/raProfiles/{raProfileUuid}/attributes/revoke/validate'
                    .replace('{authorityUuid}', encodeURI(authorityUuid))
                    .replace('{raProfileUuid}', encodeURI(raProfileUuid)),
                method: 'POST',
                headers,
                body: requestAttribute,
            },
            opts?.responseOpts,
        );
    }
}
