// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    CommentCreateRequestDto,
    CommentDto,
    CommentResponseDto,
    ErrorMessageDto,
    Resource,
} from '../models';

export interface CreateCommentRequest {
    resource: Resource;
    objectUuid: string;
    commentCreateRequestDto: CommentCreateRequestDto;
}

export interface DeleteCommentRequest {
    uuid: string;
}

export interface ListCommentsRequest {
    resource: Resource;
    objectUuid: string;
    itemsPerPage?: number;
    pageNumber?: number;
}

export interface ListRepliesRequest {
    uuid: string;
    itemsPerPage?: number;
    pageNumber?: number;
}

export interface ResolveCommentRequest {
    uuid: string;
}

export interface UnresolveCommentRequest {
    uuid: string;
}

/**
 * no description
 */
export class CommentsApi extends BaseAPI {
    /**
     * A request without parentUuid starts a new thread; with parentUuid it replies to that thread root. Threads are one level deep.
     * Post a comment or a reply on an object
     */
    createComment({ resource, objectUuid, commentCreateRequestDto }: CreateCommentRequest): Observable<CommentDto>;
    createComment(
        { resource, objectUuid, commentCreateRequestDto }: CreateCommentRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CommentDto>>;
    createComment(
        { resource, objectUuid, commentCreateRequestDto }: CreateCommentRequest,
        opts?: OperationOpts,
    ): Observable<CommentDto | AjaxResponse<CommentDto>> {
        throwIfNullOrUndefined(resource, 'resource', 'createComment');
        throwIfNullOrUndefined(objectUuid, 'objectUuid', 'createComment');
        throwIfNullOrUndefined(commentCreateRequestDto, 'commentCreateRequestDto', 'createComment');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<CommentDto>(
            {
                url: '/v1/comments/{resource}/{objectUuid}'
                    .replace('{resource}', encodeURI(resource))
                    .replace('{objectUuid}', encodeURI(objectUuid)),
                method: 'POST',
                headers,
                body: commentCreateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Deleting a thread root that has replies also deletes the replies.
     * Delete a comment
     */
    deleteComment({ uuid }: DeleteCommentRequest): Observable<void>;
    deleteComment({ uuid }: DeleteCommentRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    deleteComment({ uuid }: DeleteCommentRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteComment');

        return this.request<void>(
            {
                url: '/v1/comments/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Pages over thread roots; each root carries its reply count. Replies are paged separately.
     * List comment threads for an object
     */
    listComments({ resource, objectUuid, itemsPerPage, pageNumber }: ListCommentsRequest): Observable<CommentResponseDto>;
    listComments(
        { resource, objectUuid, itemsPerPage, pageNumber }: ListCommentsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CommentResponseDto>>;
    listComments(
        { resource, objectUuid, itemsPerPage, pageNumber }: ListCommentsRequest,
        opts?: OperationOpts,
    ): Observable<CommentResponseDto | AjaxResponse<CommentResponseDto>> {
        throwIfNullOrUndefined(resource, 'resource', 'listComments');
        throwIfNullOrUndefined(objectUuid, 'objectUuid', 'listComments');

        const queryParams: HttpQuery = {};

        if (itemsPerPage != null) {
            queryParams['itemsPerPage'] = itemsPerPage;
        }
        if (pageNumber != null) {
            queryParams['pageNumber'] = pageNumber;
        }

        return this.request<CommentResponseDto>(
            {
                url: '/v1/comments/{resource}/{objectUuid}'
                    .replace('{resource}', encodeURI(resource))
                    .replace('{objectUuid}', encodeURI(objectUuid)),
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Pages over the thread root\'s replies in creation order.
     * List replies of a comment thread
     */
    listReplies({ uuid, itemsPerPage, pageNumber }: ListRepliesRequest): Observable<CommentResponseDto>;
    listReplies({ uuid, itemsPerPage, pageNumber }: ListRepliesRequest, opts?: OperationOpts): Observable<AjaxResponse<CommentResponseDto>>;
    listReplies(
        { uuid, itemsPerPage, pageNumber }: ListRepliesRequest,
        opts?: OperationOpts,
    ): Observable<CommentResponseDto | AjaxResponse<CommentResponseDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'listReplies');

        const queryParams: HttpQuery = {};

        if (itemsPerPage != null) {
            queryParams['itemsPerPage'] = itemsPerPage;
        }
        if (pageNumber != null) {
            queryParams['pageNumber'] = pageNumber;
        }

        return this.request<CommentResponseDto>(
            {
                url: '/v1/comments/{uuid}/replies'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Thread roots only.
     * Resolve a comment thread
     */
    resolveComment({ uuid }: ResolveCommentRequest): Observable<void>;
    resolveComment({ uuid }: ResolveCommentRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    resolveComment({ uuid }: ResolveCommentRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'resolveComment');

        return this.request<void>(
            {
                url: '/v1/comments/{uuid}/resolve'.replace('{uuid}', encodeURI(uuid)),
                method: 'PATCH',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Thread roots only.
     * Reopen a resolved comment thread
     */
    unresolveComment({ uuid }: UnresolveCommentRequest): Observable<void>;
    unresolveComment({ uuid }: UnresolveCommentRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    unresolveComment({ uuid }: UnresolveCommentRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'unresolveComment');

        return this.request<void>(
            {
                url: '/v1/comments/{uuid}/unresolve'.replace('{uuid}', encodeURI(uuid)),
                method: 'PATCH',
            },
            opts?.responseOpts,
        );
    }
}
