// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    CryptographicAssetDetailDto,
    ErrorMessageDto,
    PaginationResponseDtoCryptographicAssetDto,
    SearchFieldDataByGroupDto,
    SearchRequestDto,
} from '../models';

export interface GetCryptographicAssetRequest {
    uuid: string;
}

export interface ListCryptographicAssetsRequest {
    searchRequestDto: SearchRequestDto;
}

/**
 * no description
 */
export class CryptographicAssetInventoryApi extends BaseAPI {
    /**
     * Returns the asset with its verdict provenance, its normalized properties, the elected representative payload beside the source CBOM documents that reference it — per-source payloads and occurrence evidence included — and the object identifiers producers recorded for it, refuted ones included.
     * Cryptographic asset detail
     */
    getCryptographicAsset({ uuid }: GetCryptographicAssetRequest): Observable<CryptographicAssetDetailDto>;
    getCryptographicAsset(
        { uuid }: GetCryptographicAssetRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<CryptographicAssetDetailDto>>;
    getCryptographicAsset(
        { uuid }: GetCryptographicAssetRequest,
        opts?: OperationOpts,
    ): Observable<CryptographicAssetDetailDto | AjaxResponse<CryptographicAssetDetailDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'getCryptographicAsset');

        return this.request<CryptographicAssetDetailDto>(
            {
                url: '/v1/cryptoAssets/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns the fields the list operation accepts in its filters, grouped by field source. Only the fields listed here are filterable; the platform\'s internal deduplication keys are never offered as fields.
     * Get cryptographic asset searchable fields information
     */
    getCryptographicAssetSearchableFields(): Observable<Array<SearchFieldDataByGroupDto>>;
    getCryptographicAssetSearchableFields(opts?: OperationOpts): Observable<AjaxResponse<Array<SearchFieldDataByGroupDto>>>;
    getCryptographicAssetSearchableFields(
        opts?: OperationOpts,
    ): Observable<Array<SearchFieldDataByGroupDto> | AjaxResponse<Array<SearchFieldDataByGroupDto>>> {
        return this.request<Array<SearchFieldDataByGroupDto>>(
            {
                url: '/v1/cryptoAssets/search',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns one page of the deduplicated cross-CBOM asset inventory, narrowed by the supplied filters. When no sort is supplied, rows are ordered by name ascending, then UUID ascending — a deterministic default within a deployment; a supplied sort reorders the whole result set before paging, on the fields the searchable-fields operation marks sortable. Page numbering is positional, so a sync landing between requests can shift rows across page boundaries.
     * List cryptographic assets
     */
    listCryptographicAssets({ searchRequestDto }: ListCryptographicAssetsRequest): Observable<PaginationResponseDtoCryptographicAssetDto>;
    listCryptographicAssets(
        { searchRequestDto }: ListCryptographicAssetsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<PaginationResponseDtoCryptographicAssetDto>>;
    listCryptographicAssets(
        { searchRequestDto }: ListCryptographicAssetsRequest,
        opts?: OperationOpts,
    ): Observable<PaginationResponseDtoCryptographicAssetDto | AjaxResponse<PaginationResponseDtoCryptographicAssetDto>> {
        throwIfNullOrUndefined(searchRequestDto, 'searchRequestDto', 'listCryptographicAssets');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<PaginationResponseDtoCryptographicAssetDto>(
            {
                url: '/v1/cryptoAssets',
                method: 'POST',
                headers,
                body: searchRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
