// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    BaseAttributeDto,
    CipherDataRequestDto,
    DecryptDataResponseDto,
    EncryptDataResponseDto,
    ErrorMessageDto,
    KeyAlgorithm,
    RandomDataRequestDto,
    RandomDataResponseDto,
    SignDataRequestDto,
    SignDataResponseDto,
    VerifyDataRequestDto,
    VerifyDataResponseDto,
} from '../models';

export interface DecryptDataRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
    cipherDataRequestDto: CipherDataRequestDto;
}

export interface EncryptDataRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
    cipherDataRequestDto: CipherDataRequestDto;
}

export interface ListCipherAttributesRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
    algorithm: KeyAlgorithm;
}

export interface ListDecryptAttributesRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
}

export interface ListEncryptAttributesRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
}

export interface ListRandomAttributesRequest {
    tokenInstanceUuid: string;
}

export interface ListRandomAttributesWithTokenProfileRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
}

export interface ListSignAttributesRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
}

export interface ListSignatureAttributesRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
    algorithm: KeyAlgorithm;
}

export interface ListVerifyAttributesRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
}

export interface RandomDataRequest {
    tokenInstanceUuid: string;
    randomDataRequestDto: RandomDataRequestDto;
}

export interface RandomDataWithTokenProfileRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    randomDataRequestDto: RandomDataRequestDto;
}

export interface SignDataRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
    signDataRequestDto: SignDataRequestDto;
}

export interface VerifyDataRequest {
    tokenInstanceUuid: string;
    tokenProfileUuid: string;
    uuid: string;
    keyItemUuid: string;
    verifyDataRequestDto: VerifyDataRequestDto;
}

/**
 * no description
 */
export class CryptographicOperationsControllerApi extends BaseAPI {
    /**
     * Decrypt data using a Key
     */
    decryptData({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
        cipherDataRequestDto,
    }: DecryptDataRequest): Observable<DecryptDataResponseDto>;
    decryptData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, cipherDataRequestDto }: DecryptDataRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<DecryptDataResponseDto>>;
    decryptData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, cipherDataRequestDto }: DecryptDataRequest,
        opts?: OperationOpts,
    ): Observable<DecryptDataResponseDto | AjaxResponse<DecryptDataResponseDto>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'decryptData');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'decryptData');
        throwIfNullOrUndefined(uuid, 'uuid', 'decryptData');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'decryptData');
        throwIfNullOrUndefined(cipherDataRequestDto, 'cipherDataRequestDto', 'decryptData');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<DecryptDataResponseDto>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/decrypt'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'POST',
                headers,
                body: cipherDataRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Encrypt data using a Key
     */
    encryptData({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
        cipherDataRequestDto,
    }: EncryptDataRequest): Observable<EncryptDataResponseDto>;
    encryptData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, cipherDataRequestDto }: EncryptDataRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<EncryptDataResponseDto>>;
    encryptData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, cipherDataRequestDto }: EncryptDataRequest,
        opts?: OperationOpts,
    ): Observable<EncryptDataResponseDto | AjaxResponse<EncryptDataResponseDto>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'encryptData');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'encryptData');
        throwIfNullOrUndefined(uuid, 'uuid', 'encryptData');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'encryptData');
        throwIfNullOrUndefined(cipherDataRequestDto, 'cipherDataRequestDto', 'encryptData');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<EncryptDataResponseDto>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/encrypt'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'POST',
                headers,
                body: cipherDataRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Legacy attribute discovery for v1 providers only. Use listEncryptAttributes or listDecryptAttributes instead. Not supported for v2 providers.
     * List of cipher Attributes
     */
    listCipherAttributes({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
        algorithm,
    }: ListCipherAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listCipherAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, algorithm }: ListCipherAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listCipherAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, algorithm }: ListCipherAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listCipherAttributes');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'listCipherAttributes');
        throwIfNullOrUndefined(uuid, 'uuid', 'listCipherAttributes');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'listCipherAttributes');
        throwIfNullOrUndefined(algorithm, 'algorithm', 'listCipherAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/cipher/{algorithm}/attributes'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid))
                    .replace('{algorithm}', encodeURI(algorithm)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns the decryption attribute schema for the specified token, profile and key item.
     * List decryption attributes
     */
    listDecryptAttributes({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
    }: ListDecryptAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listDecryptAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListDecryptAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listDecryptAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListDecryptAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listDecryptAttributes');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'listDecryptAttributes');
        throwIfNullOrUndefined(uuid, 'uuid', 'listDecryptAttributes');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'listDecryptAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/decrypt/attributes'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns the encryption attribute schema for the specified token, profile and key item.
     * List encryption attributes
     */
    listEncryptAttributes({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
    }: ListEncryptAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listEncryptAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListEncryptAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listEncryptAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListEncryptAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listEncryptAttributes');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'listEncryptAttributes');
        throwIfNullOrUndefined(uuid, 'uuid', 'listEncryptAttributes');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'listEncryptAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/encrypt/attributes'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Serves v1 tokens. A v2 token scopes random-data generation by token profile and must use listRandomAttributesWithTokenProfile instead.
     * List of random generator Attributes
     */
    listRandomAttributes({ tokenInstanceUuid }: ListRandomAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listRandomAttributes(
        { tokenInstanceUuid }: ListRandomAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listRandomAttributes(
        { tokenInstanceUuid }: ListRandomAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listRandomAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/random/attributes'.replace(
                    '{tokenInstanceUuid}',
                    encodeURI(tokenInstanceUuid),
                ),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * A cryptography provider v2 token requires this form, because its contract scopes random-data generation by token profile. A v1 token is served here too, so a client needs no version detection; the token profile is then ignored.
     * List of random generator Attributes for a token profile
     */
    listRandomAttributesWithTokenProfile({
        tokenInstanceUuid,
        tokenProfileUuid,
    }: ListRandomAttributesWithTokenProfileRequest): Observable<Array<BaseAttributeDto>>;
    listRandomAttributesWithTokenProfile(
        { tokenInstanceUuid, tokenProfileUuid }: ListRandomAttributesWithTokenProfileRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listRandomAttributesWithTokenProfile(
        { tokenInstanceUuid, tokenProfileUuid }: ListRandomAttributesWithTokenProfileRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listRandomAttributesWithTokenProfile');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'listRandomAttributesWithTokenProfile');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/random/attributes'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns the signing attribute schema for the specified token, profile and key item.
     * List signing attributes
     */
    listSignAttributes({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
    }: ListSignAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listSignAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListSignAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listSignAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListSignAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listSignAttributes');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'listSignAttributes');
        throwIfNullOrUndefined(uuid, 'uuid', 'listSignAttributes');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'listSignAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/sign/attributes'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Legacy attribute discovery for v1 providers only. Use listSignAttributes or listVerifyAttributes instead. Not supported for v2 providers.
     * List of signature Attributes
     */
    listSignatureAttributes({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
        algorithm,
    }: ListSignatureAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listSignatureAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, algorithm }: ListSignatureAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listSignatureAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, algorithm }: ListSignatureAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listSignatureAttributes');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'listSignatureAttributes');
        throwIfNullOrUndefined(uuid, 'uuid', 'listSignatureAttributes');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'listSignatureAttributes');
        throwIfNullOrUndefined(algorithm, 'algorithm', 'listSignatureAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/signature/{algorithm}/attributes'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid))
                    .replace('{algorithm}', encodeURI(algorithm)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Returns the verification attribute schema for the specified token, profile and key item.
     * List verification attributes
     */
    listVerifyAttributes({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
    }: ListVerifyAttributesRequest): Observable<Array<BaseAttributeDto>>;
    listVerifyAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListVerifyAttributesRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<Array<BaseAttributeDto>>>;
    listVerifyAttributes(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid }: ListVerifyAttributesRequest,
        opts?: OperationOpts,
    ): Observable<Array<BaseAttributeDto> | AjaxResponse<Array<BaseAttributeDto>>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'listVerifyAttributes');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'listVerifyAttributes');
        throwIfNullOrUndefined(uuid, 'uuid', 'listVerifyAttributes');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'listVerifyAttributes');

        return this.request<Array<BaseAttributeDto>>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/verify/attributes'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Serves v1 tokens. A v2 token scopes random-data generation by token profile and must use randomDataWithTokenProfile instead.
     * Generate random data
     */
    randomData({ tokenInstanceUuid, randomDataRequestDto }: RandomDataRequest): Observable<RandomDataResponseDto>;
    randomData(
        { tokenInstanceUuid, randomDataRequestDto }: RandomDataRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<RandomDataResponseDto>>;
    randomData(
        { tokenInstanceUuid, randomDataRequestDto }: RandomDataRequest,
        opts?: OperationOpts,
    ): Observable<RandomDataResponseDto | AjaxResponse<RandomDataResponseDto>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'randomData');
        throwIfNullOrUndefined(randomDataRequestDto, 'randomDataRequestDto', 'randomData');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<RandomDataResponseDto>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/random'.replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid)),
                method: 'POST',
                headers,
                body: randomDataRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * A cryptography provider v2 token requires this form, because its contract scopes random-data generation by token profile. A v1 token is served here too, so a client needs no version detection; the token profile is then ignored.
     * Generate random data with a token profile
     */
    randomDataWithTokenProfile({
        tokenInstanceUuid,
        tokenProfileUuid,
        randomDataRequestDto,
    }: RandomDataWithTokenProfileRequest): Observable<RandomDataResponseDto>;
    randomDataWithTokenProfile(
        { tokenInstanceUuid, tokenProfileUuid, randomDataRequestDto }: RandomDataWithTokenProfileRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<RandomDataResponseDto>>;
    randomDataWithTokenProfile(
        { tokenInstanceUuid, tokenProfileUuid, randomDataRequestDto }: RandomDataWithTokenProfileRequest,
        opts?: OperationOpts,
    ): Observable<RandomDataResponseDto | AjaxResponse<RandomDataResponseDto>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'randomDataWithTokenProfile');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'randomDataWithTokenProfile');
        throwIfNullOrUndefined(randomDataRequestDto, 'randomDataRequestDto', 'randomDataWithTokenProfile');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<RandomDataResponseDto>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/random'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid)),
                method: 'POST',
                headers,
                body: randomDataRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Sign data using a Key
     */
    signData({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
        signDataRequestDto,
    }: SignDataRequest): Observable<SignDataResponseDto>;
    signData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, signDataRequestDto }: SignDataRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<SignDataResponseDto>>;
    signData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, signDataRequestDto }: SignDataRequest,
        opts?: OperationOpts,
    ): Observable<SignDataResponseDto | AjaxResponse<SignDataResponseDto>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'signData');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'signData');
        throwIfNullOrUndefined(uuid, 'uuid', 'signData');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'signData');
        throwIfNullOrUndefined(signDataRequestDto, 'signDataRequestDto', 'signData');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<SignDataResponseDto>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/sign'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'POST',
                headers,
                body: signDataRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Verify data using a Key
     */
    verifyData({
        tokenInstanceUuid,
        tokenProfileUuid,
        uuid,
        keyItemUuid,
        verifyDataRequestDto,
    }: VerifyDataRequest): Observable<VerifyDataResponseDto>;
    verifyData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, verifyDataRequestDto }: VerifyDataRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<VerifyDataResponseDto>>;
    verifyData(
        { tokenInstanceUuid, tokenProfileUuid, uuid, keyItemUuid, verifyDataRequestDto }: VerifyDataRequest,
        opts?: OperationOpts,
    ): Observable<VerifyDataResponseDto | AjaxResponse<VerifyDataResponseDto>> {
        throwIfNullOrUndefined(tokenInstanceUuid, 'tokenInstanceUuid', 'verifyData');
        throwIfNullOrUndefined(tokenProfileUuid, 'tokenProfileUuid', 'verifyData');
        throwIfNullOrUndefined(uuid, 'uuid', 'verifyData');
        throwIfNullOrUndefined(keyItemUuid, 'keyItemUuid', 'verifyData');
        throwIfNullOrUndefined(verifyDataRequestDto, 'verifyDataRequestDto', 'verifyData');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<VerifyDataResponseDto>(
            {
                url: '/v1/operations/tokens/{tokenInstanceUuid}/tokenProfiles/{tokenProfileUuid}/keys/{uuid}/items/{keyItemUuid}/verify'
                    .replace('{tokenInstanceUuid}', encodeURI(tokenInstanceUuid))
                    .replace('{tokenProfileUuid}', encodeURI(tokenProfileUuid))
                    .replace('{uuid}', encodeURI(uuid))
                    .replace('{keyItemUuid}', encodeURI(keyItemUuid)),
                method: 'POST',
                headers,
                body: verifyDataRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
