// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined } from '../runtime';
import type { OperationOpts, HttpHeaders } from '../runtime';
import type { AuthenticationServiceExceptionDto, ErrorMessageDto, InspectionRequestDto, InspectionResponseDto } from '../models';

export interface InspectRequest {
    inspectionRequestDto: InspectionRequestDto;
}

/**
 * no description
 */
export class InspectionApi extends BaseAPI {
    /**
     * Report what an uploaded file holds, without importing or storing anything.  The file travels base64-encoded in `file`, like every upload in the platform, and is held in memory rather than written anywhere; it is never echoed in an error, since it may carry key material. Every container the platform understands is accepted, so a caller uploads once and then decides: PKCS#12 in any composition, a PEM bundle of certificates with at most one private key, a standalone PKCS#8 key, plain or encrypted, an OpenSSL traditional PEM key, an OpenSSH private key, a single certificate as PEM or DER, and PKCS#7. The container is recognised by its content, not by its file name. JKS and JCEKS stores are read too.  Nothing here has to be carried into a later operation. Each entry is reported with a reference derived from the entry\'s own content, so an operation given that reference acts on that content whichever file it arrives with. Read a file when a user should see what is inside before anything is imported; a caller that already knows what it is sending does not need to.
     * Read an uploaded file
     */
    inspect({ inspectionRequestDto }: InspectRequest): Observable<InspectionResponseDto>;
    inspect({ inspectionRequestDto }: InspectRequest, opts?: OperationOpts): Observable<AjaxResponse<InspectionResponseDto>>;
    inspect(
        { inspectionRequestDto }: InspectRequest,
        opts?: OperationOpts,
    ): Observable<InspectionResponseDto | AjaxResponse<InspectionResponseDto>> {
        throwIfNullOrUndefined(inspectionRequestDto, 'inspectionRequestDto', 'inspect');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<InspectionResponseDto>(
            {
                url: '/v1/inspections',
                method: 'POST',
                headers,
                body: inspectionRequestDto,
            },
            opts?.responseOpts,
        );
    }
}
