// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI, throwIfNullOrUndefined, encodeURI } from '../runtime';
import type { OperationOpts, HttpHeaders, HttpQuery } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    ErrorMessageDto,
    ListViewDto,
    ListViewRequestDto,
    ListViewUpdateRequestDto,
    Resource,
} from '../models';

export interface CreateViewRequest {
    listViewRequestDto: ListViewRequestDto;
}

export interface DeleteViewRequest {
    uuid: string;
}

export interface EditViewRequest {
    uuid: string;
    listViewUpdateRequestDto: ListViewUpdateRequestDto;
}

export interface ListViewsRequest {
    resource?: Resource;
}

/**
 * no description
 */
export class ListViewApi extends BaseAPI {
    /**
     * Create a view for logged user
     */
    createView({ listViewRequestDto }: CreateViewRequest): Observable<ListViewDto>;
    createView({ listViewRequestDto }: CreateViewRequest, opts?: OperationOpts): Observable<AjaxResponse<ListViewDto>>;
    createView({ listViewRequestDto }: CreateViewRequest, opts?: OperationOpts): Observable<ListViewDto | AjaxResponse<ListViewDto>> {
        throwIfNullOrUndefined(listViewRequestDto, 'listViewRequestDto', 'createView');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ListViewDto>(
            {
                url: '/v1/listViews',
                method: 'POST',
                headers,
                body: listViewRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Delete a view of logged user
     */
    deleteView({ uuid }: DeleteViewRequest): Observable<void>;
    deleteView({ uuid }: DeleteViewRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>>;
    deleteView({ uuid }: DeleteViewRequest, opts?: OperationOpts): Observable<void | AjaxResponse<void>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'deleteView');

        return this.request<void>(
            {
                url: '/v1/listViews/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'DELETE',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Edit a view of logged user
     */
    editView({ uuid, listViewUpdateRequestDto }: EditViewRequest): Observable<ListViewDto>;
    editView({ uuid, listViewUpdateRequestDto }: EditViewRequest, opts?: OperationOpts): Observable<AjaxResponse<ListViewDto>>;
    editView(
        { uuid, listViewUpdateRequestDto }: EditViewRequest,
        opts?: OperationOpts,
    ): Observable<ListViewDto | AjaxResponse<ListViewDto>> {
        throwIfNullOrUndefined(uuid, 'uuid', 'editView');
        throwIfNullOrUndefined(listViewUpdateRequestDto, 'listViewUpdateRequestDto', 'editView');

        const headers: HttpHeaders = {
            'Content-Type': 'application/json',
        };

        return this.request<ListViewDto>(
            {
                url: '/v1/listViews/{uuid}'.replace('{uuid}', encodeURI(uuid)),
                method: 'PUT',
                headers,
                body: listViewUpdateRequestDto,
            },
            opts?.responseOpts,
        );
    }

    /**
     * List views of logged user
     */
    listViews({ resource }: ListViewsRequest): Observable<Array<ListViewDto>>;
    listViews({ resource }: ListViewsRequest, opts?: OperationOpts): Observable<AjaxResponse<Array<ListViewDto>>>;
    listViews({ resource }: ListViewsRequest, opts?: OperationOpts): Observable<Array<ListViewDto> | AjaxResponse<Array<ListViewDto>>> {
        const queryParams: HttpQuery = {};

        if (resource != null) {
            queryParams['resource'] = resource;
        }

        return this.request<Array<ListViewDto>>(
            {
                url: '/v1/listViews',
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }
}
