// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.20.0-SNAPSHOT
 * Contact: ilm@omnitrust.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Observable } from 'rxjs';
import type { AjaxResponse } from 'rxjs/ajax';
import { BaseAPI } from '../runtime';
import type { OperationOpts, HttpQuery } from '../runtime';
import type {
    AuthenticationServiceExceptionDto,
    CryptographicAssetStatisticsDto,
    ErrorMessageDto,
    SigningRecordStatisticsDto,
    SigningRecordStatisticsPeriod,
    StatisticsDto,
} from '../models';

export interface GetSigningRecordStatisticsRequest {
    period?: SigningRecordStatisticsPeriod;
}

export interface GetStatisticsRequest {
    includeArchived?: boolean;
}

/**
 * no description
 */
export class StatisticsDashboardApi extends BaseAPI {
    /**
     * Returns count badges, distribution maps and the sync-completeness block for the cross-CBOM cryptographic asset inventory. Counts are computed over deduplicated assets, so an asset referenced by several CBOM documents counts once.
     * Get Cryptographic Asset Inventory dashboard statistics
     */
    getCryptographicAssetStatistics(): Observable<CryptographicAssetStatisticsDto>;
    getCryptographicAssetStatistics(opts?: OperationOpts): Observable<AjaxResponse<CryptographicAssetStatisticsDto>>;
    getCryptographicAssetStatistics(
        opts?: OperationOpts,
    ): Observable<CryptographicAssetStatisticsDto | AjaxResponse<CryptographicAssetStatisticsDto>> {
        return this.request<CryptographicAssetStatisticsDto>(
            {
                url: '/v1/statistics/cryptoAssets',
                method: 'GET',
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get Signing Records dashboard statistics
     */
    getSigningRecordStatistics({ period }: GetSigningRecordStatisticsRequest): Observable<SigningRecordStatisticsDto>;
    getSigningRecordStatistics(
        { period }: GetSigningRecordStatisticsRequest,
        opts?: OperationOpts,
    ): Observable<AjaxResponse<SigningRecordStatisticsDto>>;
    getSigningRecordStatistics(
        { period }: GetSigningRecordStatisticsRequest,
        opts?: OperationOpts,
    ): Observable<SigningRecordStatisticsDto | AjaxResponse<SigningRecordStatisticsDto>> {
        const queryParams: HttpQuery = {};

        if (period != null) {
            queryParams['period'] = period;
        }

        return this.request<SigningRecordStatisticsDto>(
            {
                url: '/v1/statistics/signingRecords',
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }

    /**
     * Get Dashboard/Statistics Details
     */
    getStatistics({ includeArchived }: GetStatisticsRequest): Observable<StatisticsDto>;
    getStatistics({ includeArchived }: GetStatisticsRequest, opts?: OperationOpts): Observable<AjaxResponse<StatisticsDto>>;
    getStatistics(
        { includeArchived }: GetStatisticsRequest,
        opts?: OperationOpts,
    ): Observable<StatisticsDto | AjaxResponse<StatisticsDto>> {
        const queryParams: HttpQuery = {};

        if (includeArchived != null) {
            queryParams['includeArchived'] = includeArchived;
        }

        return this.request<StatisticsDto>(
            {
                url: '/v1/statistics',
                method: 'GET',
                queryParams,
            },
            opts?.responseOpts,
        );
    }
}
