import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

// @ts-expect-error - plain ESM build script, no type declarations
import { CONTACT, run, setContactInSource, setContactInTree, walkTypeScriptFiles } from './set-openapi-contact.mjs';

const header = (contact: string) => `// tslint:disable
/**
 * Core API
 * REST API for ILM Core
 *
 * The version of the OpenAPI document: 2.18.1-SNAPSHOT
 * Contact: ${contact}
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 */

export interface Example {
    reference?: string;
}
`;

describe('setContactInSource', () => {
    it('replaces the address on the Contact line', () => {
        expect(setContactInSource(header('info@otilm.com'))).toBe(header(CONTACT));
    });

    it('accepts an explicit contact address', () => {
        expect(setContactInSource(header('info@otilm.com'), 'someone@example.com')).toBe(header('someone@example.com'));
    });

    it('leaves the rest of the file untouched', () => {
        const updated = setContactInSource(header('info@otilm.com'));
        expect(updated).toContain('REST API for ILM Core');
        expect(updated).toContain('export interface Example {');
        expect(updated).toContain('The version of the OpenAPI document: 2.18.1-SNAPSHOT');
    });

    it('returns sources without a Contact line unchanged', () => {
        const source = 'export interface NoHeader {}\n';
        expect(setContactInSource(source)).toBe(source);
    });

    it('rewrites only the first Contact line so file bodies are never touched', () => {
        const source = `${header('info@otilm.com')}\n// * Contact: mentioned@example.com\n`;
        expect(setContactInSource(source)).toContain('// * Contact: mentioned@example.com');
    });
});

describe('walkTypeScriptFiles and setContactInTree', () => {
    let root: string;

    beforeEach(() => {
        root = mkdtempSync(path.join(tmpdir(), 'set-contact-'));
        mkdirSync(path.join(root, 'src', 'types', 'openapi', 'models'), { recursive: true });
        mkdirSync(path.join(root, 'src', 'types', 'openapi', 'utils'), { recursive: true });
    });

    afterEach(() => {
        rmSync(root, { recursive: true, force: true });
    });

    const core = (...segments: string[]) => path.join(root, 'src', 'types', 'openapi', ...segments);

    it('finds nested .ts files and ignores other extensions', () => {
        writeFileSync(core('runtime.ts'), header('info@otilm.com'));
        writeFileSync(core('models', 'Example.ts'), header('info@otilm.com'));
        writeFileSync(core('package.json'), '{}');

        const found = [...walkTypeScriptFiles(core())].sort();

        expect(found).toEqual([core('models', 'Example.ts'), core('runtime.ts')]);
    });

    it('skips directories listed in skipDirs', () => {
        writeFileSync(core('runtime.ts'), header('info@otilm.com'));
        writeFileSync(core('utils', 'runtime.ts'), header('getinfo@czertainly.com'));

        const found = [...walkTypeScriptFiles(core(), [core('utils')])];

        expect(found).toEqual([core('runtime.ts')]);
    });

    it('rewrites matching files and reports how many changed', () => {
        writeFileSync(core('runtime.ts'), header('info@otilm.com'));
        writeFileSync(core('models', 'Example.ts'), header('info@otilm.com'));
        writeFileSync(core('models', 'Untouched.ts'), 'export interface Untouched {}\n');

        const changed = setContactInTree(core());

        expect(changed).toBe(2);
        expect(readFileSync(core('runtime.ts'), 'utf8')).toContain(`Contact: ${CONTACT}`);
        expect(readFileSync(core('models', 'Example.ts'), 'utf8')).toContain(`Contact: ${CONTACT}`);
        expect(readFileSync(core('models', 'Untouched.ts'), 'utf8')).toBe('export interface Untouched {}\n');
    });

    it('does not rewrite files that already carry the contact', () => {
        writeFileSync(core('runtime.ts'), header(CONTACT));

        expect(setContactInTree(core())).toBe(0);
    });

    it('leaves the utils tree alone when it is skipped', () => {
        writeFileSync(core('runtime.ts'), header('info@otilm.com'));
        writeFileSync(core('utils', 'runtime.ts'), header('getinfo@czertainly.com'));

        setContactInTree(core(), { skipDirs: [core('utils')] });

        expect(readFileSync(core('utils', 'runtime.ts'), 'utf8')).toContain('Contact: getinfo@czertainly.com');
    });
});

describe('run', () => {
    let root: string;

    beforeEach(() => {
        root = mkdtempSync(path.join(tmpdir(), 'set-contact-run-'));
        mkdirSync(path.join(root, 'src', 'types', 'openapi', 'utils'), { recursive: true });
    });

    afterEach(() => {
        rmSync(root, { recursive: true, force: true });
        vi.restoreAllMocks();
    });

    it('rewrites the core tree, skips utils, and logs the count', () => {
        const log = vi.spyOn(console, 'log').mockImplementation(() => {});
        const coreFile = path.join(root, 'src', 'types', 'openapi', 'runtime.ts');
        const utilsFile = path.join(root, 'src', 'types', 'openapi', 'utils', 'runtime.ts');
        writeFileSync(coreFile, header('info@otilm.com'));
        writeFileSync(utilsFile, header('getinfo@czertainly.com'));

        expect(run(root)).toBe(1);
        expect(readFileSync(coreFile, 'utf8')).toContain(`Contact: ${CONTACT}`);
        expect(readFileSync(utilsFile, 'utf8')).toContain('Contact: getinfo@czertainly.com');
        expect(log).toHaveBeenCalledWith(`set Contact: ${CONTACT} in 1 generated file(s)`);
    });
});
